force-app/main/default/objects/FundingBaseline__c/FundingBaseline__c.object-meta.xml
<CustomObject>
    <description>Object to store initial and revised KPIs for specific time periods for Funding Awards</description>
    <label>Baseline</label>
    <nameField>
        <displayFormat>BAS-{0000}</displayFormat>
        <label>Funding Baseline Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Baselines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FundingBaseline__c/fields/Baseline_Type__c.field-meta.xml
<CustomField>
    <fullName>Baseline_Type__c</fullName>
    <label>Baseline Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Award</fullName>
            </value>
            <value>
                <fullName>Phase</fullName>
            </value>
            <value>
                <fullName>Financial Year</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FundingBaseline__c/fields/Funding_Award__c.field-meta.xml
<CustomField>
    <fullName>Funding_Award__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Master Detail Relationship to parent Award</description>
    <label>Funding Award</label>
    <referenceTo>FundingAward</referenceTo>
    <relationshipLabel>Baselines</relationshipLabel>
    <relationshipName>Funding_Baselines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FundingBaseline__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Historic</fullName>
            </value>
            <value>
                <fullName>Pending Submission</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Milestones Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FundingBatch__c/FundingBatch__c.object-meta.xml
<CustomObject>
    <description>A request for funds by a local authority for the upgrade of a group of similar houses, specifying home and upgrade types, including costs and numbers for each.</description>
    <label>Batch</label>
    <nameField>
        <displayFormat>ABS-{00000000}</displayFormat>
        <label>ABS Batch Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FundingBatch__c/fields/ABS_Status__c.field-meta.xml
<CustomField>
    <fullName>ABS_Status__c</fullName>
    <label>ABS Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Review</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Pre-Approved</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Not Approved</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Returned by PSO</fullName>
            </value>
            <value>
                <fullName>Returned by GRL</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Held</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FundingBatch__c/fields/Active_Baseline__c.field-meta.xml
<CustomField>
    <fullName>Active_Baseline__c</fullName>
    <label>Active Baseline</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FundingBaseline__c.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FundingBaseline__c</referenceTo>
    <relationshipLabel>Batches (Active Baseline)</relationshipLabel>
    <relationshipName>ABS_Batches</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FundingBatch__c/fields/Funding_Award__c.field-meta.xml
<CustomField>
    <fullName>Funding_Award__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Funding Award</label>
    <referenceTo>FundingAward</referenceTo>
    <relationshipLabel>Batches</relationshipLabel>
    <relationshipName>Batches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FundingBatchMeasureSpend__c/FundingBatchMeasureSpend__c.object-meta.xml
<CustomObject>
    <description>Junctions Batches and Property Measure Type specifying quantity and costs involved with the measure specified on the batch</description>
    <label>Batch Measure Spend</label>
    <nameField>
        <displayFormat>BMS-{00000}</displayFormat>
        <label>Batch Measure Spend Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Measure Spends</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FundingBatchMeasureSpend__c/fields/Average_Price_Limit__c.field-meta.xml
<CustomField>
    <fullName>Average_Price_Limit__c</fullName>
    <inlineHelpText>For Flow use only.</inlineHelpText>
    <label>Average Price Limit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FundingBatchMeasureSpend__c/fields/Average_Spend__c.field-meta.xml
<CustomField>
    <fullName>Average_Spend__c</fullName>
    <label>Average Spend</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FundingBatchMeasureSpend__c/fields/Batch__c.field-meta.xml
<CustomField>
    <fullName>Batch__c</fullName>
    <label>Batch</label>
    <referenceTo>FundingBatch__c</referenceTo>
    <relationshipLabel>Measure Spends</relationshipLabel>
    <relationshipName>Measure_Spends</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FundingBatchMeasureSpend__c/fields/Cost_Cap_Category__c.field-meta.xml
<CustomField>
    <fullName>Cost_Cap_Category__c</fullName>
    <formula>TEXT(Measure_Type__r.Cost_Cap_Category__c)</formula>
    <label>Cost Cap Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FundingBatchMeasureSpend__c/fields/House_Count__c.field-meta.xml
<CustomField>
    <fullName>House_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <label>House Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FundingBatchMeasureSpend__c/fields/Measure_Type__c.field-meta.xml
<CustomField>
    <fullName>Measure_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Measure Type</label>
    <referenceTo>PropertyMeasureType__c</referenceTo>
    <relationshipLabel>Batch Measure Spends</relationshipLabel>
    <relationshipName>Batch_Measure_Spends</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FundingBatchMeasureSpend__c/fields/Spend__c.field-meta.xml
<CustomField>
    <fullName>Spend__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Spend</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FundingBatchMeasureSpend__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PropertyMeasureType__c/PropertyMeasureType__c.object-meta.xml
<CustomObject>
    <description>Specifies a list of Property Measure Types and related data</description>
    <label>Property Measure Type</label>
    <nameField>
        <label>Measure Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Property Measure Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PropertyMeasureType__c/fields/Average_Price_Limit__c.field-meta.xml
<CustomField>
    <fullName>Average_Price_Limit__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Average price per measure across scheme</description>
    <inlineHelpText>Measure price limits have been set for a small number of measures where the value for money of the measure type is particularly sensitive to the price of installation. GRs will be required to meet these measure price limits on average, at project level, by project closure. This means that they are permitted to install measures which are more expensive than the specified measure price limits in individual properties and batches, as long as they are within the limits on average by project closure</inlineHelpText>
    <label>Measure Price Limit</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PropertyMeasureType__c/fields/Average_Spend__c.field-meta.xml
<CustomField>
    <fullName>Average_Spend__c</fullName>
    <inlineHelpText>For flow use only.</inlineHelpText>
    <label>Average Spend</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PropertyMeasureType__c/fields/Cost_Cap_Category__c.field-meta.xml
<CustomField>
    <fullName>Cost_Cap_Category__c</fullName>
    <description>ABS Cost Cap Category</description>
    <inlineHelpText>ABS Cost Cap Category</inlineHelpText>
    <label>Cost Cap Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Energy Performance</fullName>
            </value>
            <value>
                <fullName>Low Carbon Heat</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PropertyMeasureType__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Used in the BatchMeasureMix apex Class</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Historic</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>DESNZ Approved</fullName>
            </value>
            <value>
                <fullName>Custom Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AbsAwardMeasureSpendAverages_Test.cls
@istest
public with sharing class AbsAwardMeasureSpendAverages_Test {
    
    @istest
    public static void getAwardMeasureSpendAverages_happyPath(){
        FundingAward fa1 = new FundingAward();
        insert fa1;
        FundingBaseline__c awardBaseline = new FundingBaseline__c(Baseline_Type__c = 'Award');
        awardBaseline.Funding_Award__c = fa1.Id;
        awardBaseline.Status__c = 'Active';
        insert awardBaseline;

        FundingBatch__c fb1 = new FundingBatch__c(Funding_Award__c = fa1.Id, Active_Baseline__c = awardBaseline.Id, ABS_Status__c = 'Approved');
        FundingBatch__c fb2 = new FundingBatch__c(Funding_Award__c = fa1.Id, Active_Baseline__c = awardBaseline.Id, ABS_Status__c = 'Approved');
        List<FundingBatch__c> fbs = new List<FundingBatch__c>{fb1, fb2};
        insert fbs;

        PropertyMeasureType__c pmt = new PropertyMeasureType__c(Name = 'Insulation', Average_Price_Limit__c = 12000);
        pmt.Cost_Cap_Category__c = 'Energy Performance';
        insert pmt;

        FundingBatchMeasureSpend__c fbms = new FundingBatchMeasureSpend__c();
        fbms.Batch__c = fb1.Id;
        fbms.Spend__c = 1;
        fbms.House_Count__c = 1; 
        fbms.Measure_Type__c = pmt.Id;

        FundingBatchMeasureSpend__c fbms2 = new FundingBatchMeasureSpend__c();
        fbms2.Batch__c = fb2.Id;
        fbms2.Spend__c = 3;
        fbms2.House_Count__c = 1; 
        fbms2.Measure_Type__c = pmt.Id;

        List<FundingBatchMeasureSpend__c> fbmss = new List<FundingBatchMeasureSpend__c>{fbms, fbms2};
        insert fbmss;

        Test.startTest();
        List<AbsAwardMeasureSpendAverages.MeasureSpend> response = AbsAwardMeasureSpendAverages.getAwardMeasureSpendAverages(new List<Id>{fa1.Id});
        Test.stopTest();

        for (AbsAwardMeasureSpendAverages.MeasureSpend measureSpends : response){
            for (FundingBatchMeasureSpend__c measureSpend : measureSpends.batchMeasureSpends){
                if (measureSpend.Measure_Type__c == pmt.Id){
                    Double averageSpend = (fbms.Spend__c + fbms2.Spend__c)/(fbms.House_Count__c + fbms2.House_Count__c);
                    Assert.areEqual(averageSpend, measureSpend.Average_Spend__c, 'Average spend' );
                }
            }
        }
    }

    @istest
    public static void getAwardMeasureSpendAverages_nullAwardIdList(){
        
        List<Id> faIds;
        Test.startTest();
        List<AbsAwardMeasureSpendAverages.MeasureSpend> response = AbsAwardMeasureSpendAverages.getAwardMeasureSpendAverages(faIds);
        Test.stopTest();
        Assert.areEqual(0, response.size(), 'number of response records');
    }
}