force-app/main/default/objects/FundingBaseline__c/FundingBaseline__c.object-meta.xml
<CustomObject>
    <description>Object to store initial and revised KPIs for specific time periods for Funding Awards</description>
    <label>Baseline</label>
    <nameField>
        <displayFormat>BAS-{0000}</displayFormat>
        <label>Funding Baseline Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Baselines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FundingBaseline__c/fields/ABS_FY_Grant_Spend_Rollup__c.field-meta.xml
<CustomField>
    <fullName>ABS_FY_Grant_Spend_Rollup__c</fullName>
    <defaultValue>0</defaultValue>
    <label>ABS FY Grant Spend Rollup</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FundingBatch__c/FundingBatch__c.object-meta.xml
<CustomObject>
    <description>A request for funds by a local authority for the upgrade of a group of similar houses, specifying home and upgrade types, including costs and numbers for each.</description>
    <label>Batch</label>
    <nameField>
        <displayFormat>ABS-{00000000}</displayFormat>
        <label>ABS Batch Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FundingBatch__c/fields/ABS_Status__c.field-meta.xml
<CustomField>
    <fullName>ABS_Status__c</fullName>
    <label>ABS Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Review</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Pre-Approved</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Not Approved</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Returned by PSO</fullName>
            </value>
            <value>
                <fullName>Returned by GRL</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Held</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FundingBatch__c/fields/Funding_Used_In_2nd_FY__c.field-meta.xml
<CustomField>
    <fullName>Funding_Used_In_2nd_FY__c</fullName>
    <label>Funding Used In 2nd FY of Batch</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FundingBatch__c/fields/Funding_Used_value__c.field-meta.xml
<CustomField>
    <fullName>Funding_Used_value__c</fullName>
    <label>Funding Used In current FY of Batch</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FundingBatch__c/fields/FY1_Baseline__c.field-meta.xml
<CustomField>
    <fullName>FY1_Baseline__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Batch 1st FY Baseline</label>
    <referenceTo>FundingBaseline__c</referenceTo>
    <relationshipLabel>Batches (FY1 Baseline)</relationshipLabel>
    <relationshipName>Batches_FY1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FundingBatch__c/fields/FY2_Baseline__c.field-meta.xml
<CustomField>
    <fullName>FY2_Baseline__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Batch 2nd FY Baseline</label>
    <referenceTo>FundingBaseline__c</referenceTo>
    <relationshipLabel>Batches (FY2 Baseline)</relationshipLabel>
    <relationshipName>Batches_FY2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FundingBatch__c/fields/FY3_Baseline__c.field-meta.xml
<CustomField>
    <fullName>FY3_Baseline__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Batch 3rd FY Baseline</label>
    <referenceTo>FundingBaseline__c</referenceTo>
    <relationshipLabel>Batches (Batch 3rd FY Baseline)</relationshipLabel>
    <relationshipName>Batches_FY3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FundingBatch__c/fields/Total_Grant_Fund_Requested__c.field-meta.xml
<CustomField>
    <fullName>Total_Grant_Fund_Requested__c</fullName>
    <formula>(OOEP_Grant_Total__c + OOLCH_Grant_Total__c + PR100EP_Grant_Total__c + PR100LCH_Grant_Total__c + PR50EP_Grant_Total__c + PR50LCH_Grant_Total__c + SHEP_Grant_Total__c + SHLCH_Grant_Total__c) - Total_Capital_Already_Spent_Upfront__c - Paid_Total_to_Date__c - Adjustment_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Total grant funding requested for transfer to GR bank account</inlineHelpText>
    <label>Total Grant Fund Requested</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FundingBatch__c/fields/Version_Status__c.field-meta.xml
<CustomField>
    <fullName>Version_Status__c</fullName>
    <description>Defaults to draft, is flow fast field updated to active when the batch is set to ABS_Status approved, is set to historic when a new batch version is created</description>
    <label>Version Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Historic</fullName>
            </value>
            <value>
                <fullName>Adjusted</fullName>
            </value>
            <value>
                <fullName>Discontinued</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AbsBatchTriggerHandler.cls
public without sharing class AbsBatchTriggerHandler {

    public static List<FundingBatch__c> onAfterUpdate(List<FundingBatch__c> newBatches, Map<Id, FundingBatch__c> oldBatches){
        Set<Id> baselineIds = new Set<Id>();
        for (FundingBatch__c fb : newBatches){
            FundingBatch__c oldFb = oldBatches.get(fb.Id);
            if ((fb.ABS_Status__c == 'Approved' && oldFb.ABS_Status__c != 'Approved')
                || (oldFb.ABS_Status__c == 'Approved' && fb.ABS_Status__c != 'Approved')
                || (fb.FY1_Baseline__c != oldFb.FY1_Baseline__c && fb.ABS_Status__c == 'Approved')
                || (fb.FY2_Baseline__c != oldFb.FY2_Baseline__c && fb.ABS_Status__c == 'Approved')
                || (fb.FY3_Baseline__c != oldFb.FY3_Baseline__c && fb.ABS_Status__c == 'Approved')
                || (fb.Version_Status__c != 'Active' && oldFb.Version_Status__c == 'Active')){ // all the conditions in which we want to recalculate FY baseline values

                if (fb.FY1_Baseline__c != null){ // sets are unique so it doesn't matter if we add the same value twice
                    baselineIds.add(fb.FY1_Baseline__c);
                }
                if (oldFb.FY1_Baseline__c != null){
                    baselineIds.add(oldFb.FY1_Baseline__c);
                }
                if (fb.FY2_Baseline__c != null){
                    baselineIds.add(fb.FY2_Baseline__c);
                }
                if (oldFb.FY2_Baseline__c != null){
                    baselineIds.add(oldFb.FY2_Baseline__c);
                }
                if (fb.FY3_Baseline__c != null){
                    baselineIds.add(fb.FY3_Baseline__c);
                }
                if (oldFb.FY3_Baseline__c != null){
                    baselineIds.add(oldFb.FY3_Baseline__c);
                }
                
            }
        }
        
        if (baselineIds.size() > 0){ // sum spends and update baselines 
            Map<Id, FundingBaseline__c> baselineUpdates = new Map<Id, FundingBaseline__c>();
            List<String> absStatus = new List<String>{'Approved', 'Closed'};
            List<FundingBatch__c> batchesOnTheBaselines = [SELECT Id, FY1_Baseline__c, FY2_Baseline__c, FY3_Baseline__c, Funding_Used_value__c, Funding_Used_In_2nd_FY__c, Total_Grant_Fund_Requested__c FROM FundingBatch__c WHERE (FY1_Baseline__c IN :baselineIds OR FY2_Baseline__c IN :baselineIds) AND Version_Status__c = 'Active' AND ABS_Status__c IN :absStatus];
            for (FundingBatch__c fb : batchesOnTheBaselines){
                if(fb.FY3_Baseline__c == null){
                    if (fb.FY2_Baseline__c == null){
                        if (fb.FY1_Baseline__c != null){
                            FundingBaseline__c baseline = baselineUpdates.get(fb.FY1_Baseline__c);
                            baselineUpdates.put(fb.FY1_Baseline__c, addToBaselineFyTotal(baseline, fb.FY1_Baseline__c, (Double)(fb.Total_Grant_Fund_Requested__c ?? 0)));
                        }
                    }else{
                        if (fb.FY1_Baseline__c != null){
                            FundingBaseline__c baseline = baselineUpdates.get(fb.FY1_Baseline__c);
                            baselineUpdates.put(fb.FY1_Baseline__c, addToBaselineFyTotal(baseline, fb.FY1_Baseline__c, (Double)(fb.Funding_Used_value__c ?? 0)));
                        }
                        FundingBaseline__c baseline2 = baselineUpdates.get(fb.FY2_Baseline__c);
                        Double batchFY2Spend = (fb.Total_Grant_Fund_Requested__c ?? 0) - (fb.Funding_Used_value__c ?? 0); // null coalescing operator
                        baselineUpdates.put(fb.FY2_Baseline__c, addToBaselineFyTotal(baseline2, fb.FY2_Baseline__c, batchFY2Spend));
                    }
                }else{
                    if (fb.FY2_Baseline__c == null){ //this will never get hit based on the logic in the input screens, in here for completeness/future proofing
                        if (fb.FY1_Baseline__c != null){
                            FundingBaseline__c baseline = baselineUpdates.get(fb.FY1_Baseline__c);
                            baselineUpdates.put(fb.FY1_Baseline__c, addToBaselineFyTotal(baseline, fb.FY1_Baseline__c, (Double)(fb.Total_Grant_Fund_Requested__c ?? 0)));
                        }
                    }else{
                        if (fb.FY1_Baseline__c != null){
                            FundingBaseline__c baseline = baselineUpdates.get(fb.FY1_Baseline__c);
                            baselineUpdates.put(fb.FY1_Baseline__c, addToBaselineFyTotal(baseline, fb.FY1_Baseline__c, (Double)(fb.Funding_Used_value__c ?? 0)));
                        }
                        FundingBaseline__c baseline2 = baselineUpdates.get(fb.FY2_Baseline__c);
                        Double batchFY2Spend = (fb.Funding_Used_In_2nd_FY__c ?? 0); // null coalescing operator
                        baselineUpdates.put(fb.FY2_Baseline__c, addToBaselineFyTotal(baseline2, fb.FY2_Baseline__c, batchFY2Spend));
                    }
                    FundingBaseline__c baseline3 = baselineUpdates.get(fb.FY3_Baseline__c);
                    Double batchFY3pend = (fb.Total_Grant_Fund_Requested__c ?? 0) - (fb.Funding_Used_In_2nd_FY__c ?? 0) - (fb.Funding_Used_value__c ?? 0);
                    baselineUpdates.put(fb.FY3_Baseline__c, addToBaselineFyTotal(baseline3, fb.FY3_Baseline__c, batchFY3pend));
                }
            }
            update baselineUpdates.values();
        }
        return newBatches;
    }

    public static FundingBaseline__c addToBaselineFyTotal(FundingBaseline__c baseline, Id baselineId, Double amount){
        if (amount == null){
            return baseline;
        }
        if (baseline!= null){
            if (baseline.ABS_FY_Grant_Spend_Rollup__c == null){
                baseline.ABS_FY_Grant_Spend_Rollup__c = amount;
            }else{
                baseline.ABS_FY_Grant_Spend_Rollup__c += amount;
            }
        }else{
            baseline = new FundingBaseline__c(Id = baselineId, ABS_FY_Grant_Spend_Rollup__c = amount);
        }
        return baseline;
    }
}