force-app/main/default/objects/Messaging_Snapshot__c/Messaging_Snapshot__c.object-meta.xml
<CustomObject>
    <description>generate one per month per funding award</description>
    <label>Messaging Snapshot</label>
    <nameField>
        <displayFormat>MS-{000000}</displayFormat>
        <label>Message Snapshot Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Messaging Snapshots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Messaging_Snapshot__c/fields/Average_Read_Time_By_DP__c.field-meta.xml
<CustomField>
    <fullName>Average_Read_Time_By_DP__c</fullName>
    <inlineHelpText>In seconds</inlineHelpText>
    <label>Average Read Time By DP</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Messaging_Snapshot__c/fields/Number_Of_Messages__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Messages__c</fullName>
    <label>Number Of Messages</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Messaging_Snapshot__c/fields/Number_Of_Threads__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Threads__c</fullName>
    <description>Number of child contexts plus the parent context on this parent context</description>
    <inlineHelpText>Number of child contexts plus the parent context on this parent context</inlineHelpText>
    <label>Number Of Threads</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Messaging_Snapshot_Child__c/Messaging_Snapshot_Child__c.object-meta.xml
<CustomObject>
    <label>Messaging Snapshot Child</label>
    <nameField>
        <displayFormat>MSC-{000000}</displayFormat>
        <label>Messaging Snapshot Child Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Messaging Snapshot Children</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Messaging_Snapshot_Child__c/fields/Average_Read_Time_By_DP__c.field-meta.xml
<CustomField>
    <fullName>Average_Read_Time_By_DP__c</fullName>
    <inlineHelpText>in seconds</inlineHelpText>
    <label>Average Read Time By DP</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Messaging_Snapshot_Child__c/fields/Average_Response_Time_By_DP__c.field-meta.xml
<CustomField>
    <fullName>Average_Response_Time_By_DP__c</fullName>
    <inlineHelpText>in seconds</inlineHelpText>
    <label>Average Response Time By DP</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Messaging_Snapshot_Child__c/fields/Messaging_Snapshot__c.field-meta.xml
<CustomField>
    <fullName>Messaging_Snapshot__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Messaging Snapshot</label>
    <referenceTo>Messaging_Snapshot__c</referenceTo>
    <relationshipLabel>Messaging Snapshot Children</relationshipLabel>
    <relationshipName>Messaging_Snapshot_Children</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Messaging_Snapshot_Child__c/fields/Number_Of_Messages__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Messages__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number Of Messages</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Messaging_Snapshot_Child__c/fields/Number_Of_Messages_Read_By_DP__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Messages_Read_By_DP__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number Of Messages Read By DP</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Messaging_Snapshot_Child__c/fields/Number_Of_Messages_Responded_To_By_DP__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Messages_Responded_To_By_DP__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number Of Messages Responded To By DP</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Messaging_Snapshot_Child__c/fields/Number_Of_Unread_Messages_By_DP__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Unread_Messages_By_DP__c</fullName>
    <label>Number Of Unread Messages By DP</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Messaging_Snapshot_Child__c/fields/Number_Of_Unresponded_Messages_By_DP__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Unresponded_Messages_By_DP__c</fullName>
    <label>Number Of Unresponded Messages By DP</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/MessagingSnapshotChildTriggerHander.cls
public with sharing class MessagingSnapshotChildTriggerHander {
    
    public static List<Messaging_Snapshot_Child__c> onAfterInsert(
        List<Messaging_Snapshot_Child__c> newSnapshots
    ){
        aggregateChildSnapshots(newSnapshots);
        return newSnapshots;
    }

    public static List<Messaging_Snapshot_Child__c> onAfterUpdate(
        List<Messaging_Snapshot_Child__c> newSnapshots, 
        Map<Id, Messaging_Snapshot_Child__c> oldSnapshots
    ){
        aggregateChildSnapshots(newSnapshots);
        return newSnapshots;
    }

    public static void aggregateChildSnapshots(List<Messaging_Snapshot_Child__c> snapshots){
        Set<Id> snapshotIds = new Set<Id>();
        for (Messaging_Snapshot_Child__c snapshot : snapshots){
            snapshotIds.add(snapshot.Messaging_Snapshot__c);
        }
        Map<String, Object> bindParams = new Map<String, Object>{'snapshotIds'=>snapshotIds}; 
        List<String> snapshotFields = new List<String>(Schema.Messaging_Snapshot__c.SObjectType.getDescribe().fields.getMap().keySet());
        List<String> snapshotChildFields = new List<String>(Schema.Messaging_Snapshot_Child__c.SObjectType.getDescribe().fields.getMap().keySet());
        String snapshotQuery = 'SELECT ' + String.join(snapshotFields, ',') + 
        ', (SELECT ' + String.join(snapshotChildFields, ',') + ' FROM Messaging_Snapshot_Children__r)'
        + 'FROM Messaging_Snapshot__c WHERE Id IN :snapshotIds';
        List<Messaging_Snapshot__c> snapshotParents = Database.queryWithBinds(
                snapshotQuery, 
                bindParams, 
                AccessLevel.SYSTEM_MODE
            );

        for (Messaging_Snapshot__c snapshotParent : snapshotParents){
            snapshotParent.Number_Of_Messages__c = 0;
            snapshotParent.Number_Of_Unresponded_Messages_By_DP__c = 0;
            snapshotParent.Number_Of_Unread_Messages_By_DP__c = 0;

            Decimal totalResponseTime = 0;
            Decimal totalNumberOfMessagesRespondedTo = 0;
            Decimal totalReadTime = 0;
            Decimal totalNumberOfMessagesRead = 0;
            for (Messaging_Snapshot_Child__c childSnapshot : snapshotParent.Messaging_Snapshot_Children__r){
                snapshotParent.Number_Of_Messages__c += (childSnapshot.Number_Of_Messages__c ?? 0);
                snapshotParent.Number_Of_Unresponded_Messages_By_DP__c += (childSnapshot.Number_Of_Unresponded_Messages_By_DP__c ?? 0);
                snapshotParent.Number_Of_Unread_Messages_By_DP__c += (childSnapshot.Number_Of_Unread_Messages_By_DP__c ?? 0);

                totalNumberOfMessagesRespondedTo += (childSnapshot.Number_Of_Messages_Responded_To_By_DP__c ?? 0);
                totalResponseTime += (childSnapshot.Number_Of_Messages_Responded_To_By_DP__c ?? 0) * (childSnapshot.Average_Response_Time_By_DP__c ?? 0);
                totalNumberOfMessagesRead += (childSnapshot.Number_Of_Messages_Read_By_DP__c ?? 0);
                totalReadTime += (childSnapshot.Number_Of_Messages_Read_By_DP__c ?? 0) * (childSnapshot.Average_Read_Time_By_DP__c ?? 0);

            }
            if (totalNumberOfMessagesRespondedTo != 0){
                snapshotParent.Average_Response_Time_By_DP__c = totalResponseTime / totalNumberOfMessagesRespondedTo;
            }
            if (totalNumberOfMessagesRead != 0){
                snapshotParent.Average_Read_Time_By_DP__c = totalReadTime / totalNumberOfMessagesRead;
            }
            snapshotParent.Number_Of_Threads__c = (snapshotParent?.Messaging_Snapshot_Children__r?.size() ?? 0);

        }
        update snapshotParents;
    }
}