force-app/main/default/objects/Follow__c/Follow__c.object-meta.xml
<CustomObject>
    <description>Represents a user following a chat record.</description>
    <label>Follow</label>
    <nameField>
        <displayFormat>F-{000000}</displayFormat>
        <label>Follow No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Follows</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Follow__c/fields/Context__c.field-meta.xml
<CustomField>
    <fullName>Context__c</fullName>
    <externalId>true</externalId>
    <label>Context</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ChatFundingAwardFollowSetter.cls
public without sharing class ChatFundingAwardFollowSetter {
    @invocableMethod(label = 'Set default follows')
    public static void setDefaultFollows(){
        Map<Id, FundingAward> fas = new Map<Id, FundingAward>([SELECT Id, OwnerId FROM FundingAward]); 
        
        List<Follow__c> follows = new List<Follow__c>();
        List<Follow__Share> followShares = new List<Follow__Share>();
        for (FundingAward fa : fas.values()){
            Follow__c f = new Follow__c();
            f.Context__c = fa.Id;
            follows.add(f);            
        }

        upsert follows Context__c;

        for (Follow__c f : follows){
            Follow__Share fs = new Follow__Share();
            fs.ParentId = f.Id;
            fs.UserOrGroupId = fas.get(f.Context__c).OwnerId;
            fs.AccessLevel = 'Read';
            fs.rowCause = Schema.Follow__Share.RowCause.Messaging__c;
            followShares.add(fs);
        }

        List<Database.SaveResult> sr = Database.insert(followShares);
    }
}