force-app/main/default/objects/FundingBatch__c/FundingBatch__c.object-meta.xml
<CustomObject>
    <description>A request for funds by a local authority for the upgrade of a group of similar houses, specifying home and upgrade types, including costs and numbers for each.</description>
    <label>Batch</label>
    <nameField>
        <displayFormat>ABS-{00000000}</displayFormat>
        <label>ABS Batch Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FundingBatch__c/fields/ABS_Status__c.field-meta.xml
<CustomField>
    <fullName>ABS_Status__c</fullName>
    <label>ABS Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Review</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Pre-Approved</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Not Approved</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Returned by PSO</fullName>
            </value>
            <value>
                <fullName>Returned by GRL</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Held</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FundingBatch__c/fields/Funding_Award__c.field-meta.xml
<CustomField>
    <fullName>Funding_Award__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Funding Award</label>
    <referenceTo>FundingAward</referenceTo>
    <relationshipLabel>Batches</relationshipLabel>
    <relationshipName>Batches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FundingBatchMeasureSpend__c/FundingBatchMeasureSpend__c.object-meta.xml
<CustomObject>
    <description>Junctions Batches and Property Measure Type specifying quantity and costs involved with the measure specified on the batch</description>
    <label>Batch Measure Spend</label>
    <nameField>
        <displayFormat>BMS-{00000}</displayFormat>
        <label>Batch Measure Spend Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Measure Spends</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FundingBatchMeasureSpend__c/fields/Average_Spend__c.field-meta.xml
<CustomField>
    <fullName>Average_Spend__c</fullName>
    <label>Average Spend</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FundingBatchMeasureSpend__c/fields/Batch__c.field-meta.xml
<CustomField>
    <fullName>Batch__c</fullName>
    <label>Batch</label>
    <referenceTo>FundingBatch__c</referenceTo>
    <relationshipLabel>Measure Spends</relationshipLabel>
    <relationshipName>Measure_Spends</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FundingBatchMeasureSpend__c/fields/House_Count__c.field-meta.xml
<CustomField>
    <fullName>House_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <label>House Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FundingBatchMeasureSpend__c/fields/Measure_Type__c.field-meta.xml
<CustomField>
    <fullName>Measure_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Measure Type</label>
    <referenceTo>PropertyMeasureType__c</referenceTo>
    <relationshipLabel>Batch Measure Spends</relationshipLabel>
    <relationshipName>Batch_Measure_Spends</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FundingBatchMeasureSpend__c/fields/Spend__c.field-meta.xml
<CustomField>
    <fullName>Spend__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Spend</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PropertyMeasureType__c/PropertyMeasureType__c.object-meta.xml
<CustomObject>
    <description>Specifies a list of Property Measure Types and related data</description>
    <label>Property Measure Type</label>
    <nameField>
        <label>Measure Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Property Measure Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PropertyMeasureType__c/fields/Average_Spend__c.field-meta.xml
<CustomField>
    <fullName>Average_Spend__c</fullName>
    <inlineHelpText>For flow use only.</inlineHelpText>
    <label>Average Spend</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/AbsAwardMeasureSpendAverages.cls
public without sharing class AbsAwardMeasureSpendAverages {
   
    public static final Set<String> APPROVED_STATUS = new Set<String>{'Approved', 'Closed'};

    @invocableMethod(label = 'Calculate Measure Price Averages and Limits for a group of Awards')
    public static List<MeasureSpend> getAwardMeasureSpendAverages(List<String> fundingAwardIds){
        List<MeasureSpend> measureSpends = new List<MeasureSpend>();
        if (fundingAwardIds == null){
            return measureSpends;
        }
        Map<Id, PropertyMeasureType__c> measureTypes = new Map<Id, PropertyMeasureType__c>([SELECT Id, Name FROM PropertyMeasureType__c LIMIT 500]);
        List<AggregateResult> results = [SELECT SUM(Spend__c)totalSpend, SUM(House_Count__c)totalHomes, Measure_Type__c FROM FundingBatchMeasureSpend__c WHERE Batch__r.Funding_Award__c IN :fundingAwardIds AND Batch__r.ABS_Status__c IN :APPROVED_STATUS GROUP BY Measure_Type__c]; 
        if (results.size() == 0){
            return measureSpends;
        }

        List<FundingBatchMeasureSpend__c> batchMeasureSpends = new List<FundingBatchMeasureSpend__c>();

        Map<Id, AggregateResult> organisedResults = new Map<Id, AggregateResult>();
        for (AggregateResult result : results){
            FundingBatchMeasureSpend__c batchMeasureSpend = new FundingBatchMeasureSpend__c();
            
            Double totalSpend = (Double)result?.get('totalSpend') ?? 0;
            Double totalHomes = (Double)result?.get('totalHomes') ?? 0;
            // Default nulls to 0
            batchMeasureSpend.Spend__c = totalSpend ?? 0;
            batchMeasureSpend.House_Count__c = totalHomes ?? 0;
            batchMeasureSpend.Average_Spend__c = (totalHomes == 0) ? 0 : (totalSpend / totalHomes);
            batchMeasureSpend.Measure_Type__c = (String)result?.get('Measure_Type__c');
            batchMeasureSpend.Description__c = measureTypes?.get(batchMeasureSpend?.Measure_Type__c)?.Name; // use the description to store the name instead of doing a formula calculate that'll do a select in a loop
            batchMeasureSpends.add(batchMeasureSpend);
        }

        measureSpends.add(new MeasureSpend(batchMeasureSpends));
        return measureSpends;
    }

    public class MeasureSpend{
        @InvocableVariable
        public List<FundingBatchMeasureSpend__c> batchMeasureSpends;
        MeasureSpend(List<FundingBatchMeasureSpend__c> measureSpends){
            this.batchMeasureSpends = measureSpends;
        }
    }
}