force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Messaging_Snapshot__c/Messaging_Snapshot__c.object-meta.xml
<CustomObject>
    <description>generate one per month per funding award</description>
    <label>Messaging Snapshot</label>
    <nameField>
        <displayFormat>MS-{000000}</displayFormat>
        <label>Message Snapshot Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Messaging Snapshots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Messaging_Snapshot__c/fields/Average_Read_Time_By_DP__c.field-meta.xml
<CustomField>
    <fullName>Average_Read_Time_By_DP__c</fullName>
    <inlineHelpText>In seconds</inlineHelpText>
    <label>Average Read Time By DP</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Messaging_Snapshot__c/fields/Funding_Award__c.field-meta.xml
<CustomField>
    <fullName>Funding_Award__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Funding Award</label>
    <referenceTo>FundingAward</referenceTo>
    <relationshipName>Messaging_Shapshots</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Messaging_Snapshot__c/fields/Number_Of_Messages__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Messages__c</fullName>
    <label>Number Of Messages</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Messaging_Snapshot__c/fields/Number_Of_Threads__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Threads__c</fullName>
    <description>Number of child contexts plus the parent context on this parent context</description>
    <inlineHelpText>Number of child contexts plus the parent context on this parent context</inlineHelpText>
    <label>Number Of Threads</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Messaging_Snapshot__c/fields/Snapshot_Id__c.field-meta.xml
<CustomField>
    <fullName>Snapshot_Id__c</fullName>
    <description>Concatenation of the funding award and the date</description>
    <externalId>true</externalId>
    <label>Snapshot Id</label>
    <length>28</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Messaging_Snapshot__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <label>Start</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Messaging_Snapshot__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Current</fullName>
                <default>true</default>
                <label>Current</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Messaging_Snapshot_Child__c/Messaging_Snapshot_Child__c.object-meta.xml
<CustomObject>
    <label>Messaging Snapshot Child</label>
    <nameField>
        <displayFormat>MSC-{000000}</displayFormat>
        <label>Messaging Snapshot Child Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Messaging Snapshot Children</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Messaging_Snapshot_Child__c/fields/Average_Read_Time_By_DP__c.field-meta.xml
<CustomField>
    <fullName>Average_Read_Time_By_DP__c</fullName>
    <inlineHelpText>in seconds</inlineHelpText>
    <label>Average Read Time By DP</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Messaging_Snapshot_Child__c/fields/Average_Response_Time_By_DP__c.field-meta.xml
<CustomField>
    <fullName>Average_Response_Time_By_DP__c</fullName>
    <inlineHelpText>in seconds</inlineHelpText>
    <label>Average Response Time By DP</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Messaging_Snapshot_Child__c/fields/Funding_Award__c.field-meta.xml
<CustomField>
    <fullName>Funding_Award__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Funding Award</label>
    <referenceTo>FundingAward</referenceTo>
    <relationshipName>Messaging_Shapshot_Children</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Messaging_Snapshot_Child__c/fields/Messaging_Snapshot__c.field-meta.xml
<CustomField>
    <fullName>Messaging_Snapshot__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Messaging Snapshot</label>
    <referenceTo>Messaging_Snapshot__c</referenceTo>
    <relationshipLabel>Messaging Snapshot Children</relationshipLabel>
    <relationshipName>Messaging_Snapshot_Children</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Messaging_Snapshot_Child__c/fields/Number_Of_Messages__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Messages__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number Of Messages</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Messaging_Snapshot_Child__c/fields/Number_Of_Messages_Read_By_DP__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Messages_Read_By_DP__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number Of Messages Read By DP</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Messaging_Snapshot_Child__c/fields/Number_Of_Messages_Responded_To_By_DP__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Messages_Responded_To_By_DP__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number Of Messages Responded To By DP</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Messaging_Snapshot_Child__c/fields/Number_Of_Unread_Messages_By_DP__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Unread_Messages_By_DP__c</fullName>
    <label>Number Of Unread Messages By DP</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Messaging_Snapshot_Child__c/fields/Number_Of_Unresponded_Messages_By_DP__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Unresponded_Messages_By_DP__c</fullName>
    <label>Number Of Unresponded Messages By DP</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Messaging_Snapshot_Child__c/fields/Snapshot_Id__c.field-meta.xml
<CustomField>
    <fullName>Snapshot_Id__c</fullName>
    <externalId>true</externalId>
    <label>Snapshot Id</label>
    <length>28</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Messaging_Snapshot_Child__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Current</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MessagingSnapshotChildTH_Test.cls
@istest
public with sharing class MessagingSnapshotChildTH_Test {

    @TestSetup
    public static void makeData(){
        Date snapshotPeriod = Date.newInstance(Date.today().year(), Date.today().month(), 1);
        String period = String.valueOf(snapshotPeriod).split(' ')[0];
        FundingAward fa = new FundingAward();
        insert fa;
        
        Messaging_Snapshot__c ms = new Messaging_Snapshot__c();
        ms.Funding_Award__c = fa.Id;
        ms.Status__c = 'Current';
        ms.Start__c = snapshotPeriod;
        ms.Snapshot_Id__c = fa.Id + period;
        insert ms;

        List<Messaging_Snapshot_Child__c> mscs = new List<Messaging_Snapshot_Child__c>();
        Messaging_Snapshot_Child__c msc = new Messaging_Snapshot_Child__c();
        msc.Funding_Award__c = fa.Id;
        msc.Status__c = 'Current';
        msc.Start__c = snapshotPeriod;
        msc.Snapshot_Id__c = Stub.getId(Schema.Account.getSObjectType()) + period;
        msc.Messaging_Snapshot__c = ms.Id;
        mscs.add(msc);
        insert mscs;
    }

    @istest
    public static void aggregateChildSnapshots_ResponseTime(){
        Date snapshotPeriod = Date.newInstance(Date.today().year(), Date.today().month(), 1);
        String period = String.valueOf(snapshotPeriod).split(' ')[0];
        Messaging_Snapshot__c ms = getMessagingSnapshot();
        Messaging_Snapshot_Child__c snapshot = new Messaging_Snapshot_Child__c();
        snapshot.Messaging_Snapshot__c = ms.Id;
        snapshot.Number_Of_Messages__c = 6;
        snapshot.Number_Of_Messages_Responded_To_By_DP__c = 4;
        snapshot.Average_Response_Time_By_DP__c = 100;
        snapshot.Number_Of_Unresponded_Messages_By_DP__c = 1;
        snapshot.Snapshot_Id__c = Stub.getId(Schema.Opportunity.getSObjectType()) + period;

        Messaging_Snapshot_Child__c snapshot2 = new Messaging_Snapshot_Child__c();
        snapshot2.Messaging_Snapshot__c = ms.Id;
        snapshot2.Number_Of_Messages__c = 7;
        snapshot2.Number_Of_Messages_Responded_To_By_DP__c = 4;
        snapshot2.Average_Response_Time_By_DP__c = 200;
        snapshot2.Number_Of_Unresponded_Messages_By_DP__c = 2;
        snapshot2.Snapshot_Id__c = Stub.getId(Schema.Opportunity.getSObjectType()) + period;

        insert new List<Messaging_Snapshot_Child__c>{snapshot, snapshot2};

        Test.startTest();
        MessagingSnapshotChildTriggerHander.aggregateChildSnapshots(new List<Messaging_Snapshot_Child__c>{snapshot, snapshot2});
        Test.stopTest();
        
        Messaging_Snapshot__c msAfter = getMessagingSnapshot(ms.Id);
        Assert.areEqual(3, msAfter.Number_Of_Unresponded_Messages_By_DP__c, 'parent snapshot number of unresponded messages');
        Assert.areEqual(13, msAfter.Number_Of_Messages__c, 'parent snapshot number of messages');
        Assert.areEqual(150, msAfter.Average_Response_Time_By_DP__c, 'parent snapshot average response time');
    } 

    @istest
    public static void aggregateChildSnapshots_ReadTime(){
        Date snapshotPeriod = Date.newInstance(Date.today().year(), Date.today().month(), 1);
        String period = String.valueOf(snapshotPeriod).split(' ')[0];
        Messaging_Snapshot__c ms = getMessagingSnapshot();
        Messaging_Snapshot_Child__c snapshot = new Messaging_Snapshot_Child__c();
        snapshot.Messaging_Snapshot__c = ms.Id;
        snapshot.Number_Of_Messages__c = 5;
        snapshot.Number_Of_Messages_Read_By_DP__c = 3;
        snapshot.Average_Read_Time_By_DP__c = 100;
        snapshot.Number_Of_Unread_Messages_By_DP__c = 1;
        snapshot.Snapshot_Id__c = Stub.getId(Schema.Asset.getSObjectType()) + period;

        Messaging_Snapshot_Child__c snapshot2 = new Messaging_Snapshot_Child__c();
        snapshot2.Messaging_Snapshot__c = ms.Id;
        snapshot2.Number_Of_Messages__c = 5;
        snapshot2.Number_Of_Messages_Read_By_DP__c = 3;
        snapshot2.Average_Read_Time_By_DP__c = 500;
        snapshot2.Number_Of_Unread_Messages_By_DP__c = 1;
        snapshot2.Snapshot_Id__c = Stub.getId(Schema.Asset.getSObjectType()) + period;

        insert new List<Messaging_Snapshot_Child__c>{snapshot, snapshot2};
        
        Test.startTest();
        MessagingSnapshotChildTriggerHander.aggregateChildSnapshots(new List<Messaging_Snapshot_Child__c>{snapshot, snapshot2});
        Test.stopTest();
        Messaging_Snapshot__c msAfter = getMessagingSnapshot(ms.Id);
        Assert.areEqual(2, msAfter.Number_Of_Unread_Messages_By_DP__c, 'parent snapshot number of unread messages');
        Assert.areEqual(10, msAfter.Number_Of_Messages__c, 'parent snapshot number of messages');
        Assert.areEqual(300, msAfter.Average_Read_Time_By_DP__c, 'parent snapshot average read time');
    } 

    @istest
    public static void onAfterInsert(){
        Date snapshotPeriod = Date.newInstance(Date.today().year(), Date.today().month(), 1);
        String period = String.valueOf(snapshotPeriod).split(' ')[0];
        Messaging_Snapshot__c ms = getMessagingSnapshot();
        Messaging_Snapshot_Child__c snapshot = new Messaging_Snapshot_Child__c();
        snapshot.Messaging_Snapshot__c = ms.Id;
        snapshot.Number_Of_Messages__c = 3;
        snapshot.Number_Of_Messages_Responded_To_By_DP__c = 2;
        snapshot.Average_Response_Time_By_DP__c = 200;
        snapshot.Number_Of_Unresponded_Messages_By_DP__c = 0;
        snapshot.Snapshot_Id__c = Stub.getId(Schema.Contact.getSObjectType()) + period;
        Test.startTest();
        insert snapshot;
        Test.stopTest();
        Messaging_Snapshot__c msAfter = getMessagingSnapshot(ms.Id);

        Assert.areEqual((ms.Number_Of_Threads__c ?? 0) + 1, msAfter.Number_Of_Threads__c, 'the number of threads on the award should have increased by 1 on insert');
    }

    @istest
    public static void onAfterUpdate(){
        Messaging_Snapshot__c ms = [SELECT Id, Number_Of_Threads__c, Number_Of_Messages__c, (SELECT Id, Number_Of_Messages__c FROM Messaging_Snapshot_Children__r) FROM Messaging_Snapshot__c WHERE Id IN (SELECT Messaging_Snapshot__c FROM Messaging_Snapshot_Child__c) LIMIT 1];
        Messaging_Snapshot_Child__c msc = ms.Messaging_Snapshot_Children__r.get(0);
        msc.Number_Of_Messages__c += 1;
        Test.startTest();
        update msc;
        Test.stopTest();
        Messaging_Snapshot__c msAfter = getMessagingSnapshot(ms.Id);
        Assert.areEqual(ms.Number_Of_Threads__c, msAfter.Number_Of_Threads__c, 'the number of threads on the award should not increased by 1 on update');
        Assert.areEqual(ms.Number_Of_Messages__c + 1, msAfter.Number_Of_Messages__c, 'the number of messages the parent snapshot should have after the update');
    }

    public static Messaging_Snapshot__c getMessagingSnapshot(){
        return getMessagingSnapshot(null);
    }

    public static Messaging_Snapshot__c getMessagingSnapshot(Id snapshotId){
        Map<String, Object> bindParams = new Map<String, Object>{'snapshotId'=>snapshotId}; 
        String whereClause = ' WHERE Id = :snapshotId ';
        if (snapshotId == null){
            whereClause = '';
        }
        List<String> snapshotFields = new List<String>(Schema.Messaging_Snapshot__c.SObjectType.getDescribe().fields.getMap().keySet());
        String snapshotQuery = 'SELECT ' + String.join(snapshotFields, ',') + ' FROM Messaging_Snapshot__c ' + whereClause + ' LIMIT 1';
        List<Messaging_Snapshot__c> snapshots =
            (List<Messaging_Snapshot__c>)Database.queryWithBinds(
                snapshotQuery, 
                bindParams, 
                AccessLevel.SYSTEM_MODE
            );
        return snapshots.get(0);
    }
}