force-app/main/default/objects/Change_Control_Request_Line_Item__c/Change_Control_Request_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Change Control Request Line Item</label>
    <nameField>
        <displayFormat>CRLIN-{000000}</displayFormat>
        <label>Change Control Request Line Item No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Change Control Request Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Change_Control_Request_Line_Item__c/fields/Baseline__c.field-meta.xml
<CustomField>
    <fullName>Baseline__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Baseline</label>
    <referenceTo>FundingBaseline__c</referenceTo>
    <relationshipLabel>Change Control Request Line Items</relationshipLabel>
    <relationshipName>Change_Control_Request_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Change_Control_Request_Line_Item__c/fields/Baseline_Measure_Description__c.field-meta.xml
<CustomField>
    <fullName>Baseline_Measure_Description__c</fullName>
    <description>Populated from CCR form and will be a mirror of the related baseline measure records description.</description>
    <label>Baseline Measure Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Change_Control_Request_Line_Item__c/fields/Baseline_Measure_Description_Previous__c.field-meta.xml
<CustomField>
    <fullName>Baseline_Measure_Description_Previous__c</fullName>
    <description>Copies the value from the related baseline measure at the time of line item creation. Used to store the previous value of the description if changed via the change control request form on the GMS portal.</description>
    <label>Baseline Measure Description (Previous)</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Change_Control_Request_Line_Item__c/fields/Cache__c.field-meta.xml
<CustomField>
    <fullName>Cache__c</fullName>
    <description>Used to cache values on the record during processing</description>
    <label>Cache</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Change_Control_Request_Line_Item__c/fields/End_Date_Previous__c.field-meta.xml
<CustomField>
    <fullName>End_Date_Previous__c</fullName>
    <label>End Date Previous</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Change_Control_Request_Line_Item__c/fields/Start_Date_Previous__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_Previous__c</fullName>
    <label>Start Date Previous</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Change_Control_Request_Line_Item__c/fields/Total_number_of_homes_to_be_upgraded__c.field-meta.xml
<CustomField>
    <fullName>Total_number_of_homes_to_be_upgraded__c</fullName>
    <label>No. of homes to be upgraded</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Change_Control_Request_Line_Item__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of record this change control request is for</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Award Baseline</fullName>
            </value>
            <value>
                <fullName>Sub Baseline</fullName>
            </value>
            <value>
                <fullName>Forecast</fullName>
            </value>
            <value>
                <fullName>Consortium Member Change</fullName>
            </value>
            <value>
                <fullName>Award Rename</fullName>
            </value>
            <value>
                <fullName>Grant Recipient Lead Change</fullName>
            </value>
            <value>
                <fullName>Measure Detail</fullName>
            </value>
            <value>
                <fullName>Supplier</fullName>
            </value>
            <value>
                <fullName>Project End Date</fullName>
            </value>
            <value>
                <fullName>Phase Change</fullName>
            </value>
            <value>
                <fullName>Income Verification</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Change_Control_Request_Line_Item__c/recordTypes/SHF_Challenge_Fund.recordType-meta.xml
<RecordType>
    <fullName>SHF_Challenge_Fund</fullName>
    <active>true</active>
    <label>SHF Challenge Fund</label>
</RecordType>

force-app/main/default/objects/FundingBaseline__c/FundingBaseline__c.object-meta.xml
<CustomObject>
    <description>Object to store initial and revised KPIs for specific time periods for Funding Awards</description>
    <label>Baseline</label>
    <nameField>
        <displayFormat>BAS-{0000}</displayFormat>
        <label>Funding Baseline Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Baselines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FundingBaseline__c/fields/Baseline_Version__c.field-meta.xml
<CustomField>
    <fullName>Baseline_Version__c</fullName>
    <formula>IF( Parent_Time_Period__r.Record_Type_Name__c = &quot;Award Duration&quot;,Funding_Award__r.Funding_Award_Acronym__c + &quot;-&quot;, Parent_Time_Period__r.Name +&quot;-&quot;) 

+

IF(ISPICKVAL(Baseline_Type__c, &quot;Award&quot;) , &quot;Award Baseline V&quot;+TEXT(Baseline_Version_No__c), &quot;Baseline V&quot;+TEXT(Baseline_Version_No__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Baseline Version</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FundingBaseline__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Historic</fullName>
            </value>
            <value>
                <fullName>Pending Submission</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Milestones Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FundingBaseline__c/fields/Total_Homes_to_be_Upgraded__c.field-meta.xml
<CustomField>
    <fullName>Total_Homes_to_be_Upgraded__c</fullName>
    <description>This data field relates to the ‘homes completed’ KPI for both schemes. When a home is at the status of complete, it is then classed as ‘upgraded’</description>
    <inlineHelpText>This data field relates to the ‘homes completed’ KPI for both schemes. When a home is at the status of complete, it is then classed as ‘upgraded’</inlineHelpText>
    <label>Total Homes to be Upgraded</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FundingBaseline__c/recordTypes/SHF_Challenge_Fund.recordType-meta.xml
<RecordType>
    <fullName>SHF_Challenge_Fund</fullName>
    <active>true</active>
    <label>SHF Challenge Fund</label>
</RecordType>

force-app/main/default/classes/GmsCcrFormPhaseChange.cls
public without sharing class GmsCcrFormPhaseChange {
    
    @InvocableMethod(label='GMS - CCR - Convert Baselines to Phase Change Items')
    public static List<Output> getPhaseItems(List<Input> inputs){
        Id recordTypeId = Schema.Change_Control_Request_Line_Item__c.getSObjectType().getDescribe().getRecordTypeInfosByDeveloperName().get('SHF_Challenge_Fund').getRecordTypeId();
        Output output = new Output();
        List<Output> outputs = new List<Output>{output};
        List<FundingBaseline__c> baselines = inputs?.get(0)?.baselines;

        Map<Id, Change_Control_Request_Line_Item__c> initialItems = new Map<Id, Change_Control_Request_Line_Item__c>(); 
        List<Change_Control_Request_Line_Item__c> newItems = new List<Change_Control_Request_Line_Item__c>();

        if (inputs?.get(0)?.items != null){
            if (baselines == null){ // no baselines and items, just return the items 
                output.items = inputs?.get(0)?.items;
                return outputs;
            }

            if (baselines.size() == 0){ // no baselines and items, just return the items 
                output.items = inputs?.get(0)?.items;
                return outputs;
            }
            
            for (Change_Control_Request_Line_Item__c item : inputs?.get(0)?.items){
                if (item.Baseline__c == null){
                    newItems.add(item); // these are requests for new phases so add them at the end 
                }else{
                    initialItems.put(item.Baseline__c, item);
                }
            }
        }
        if (baselines == null){ // no baselines and items, just return the items 
            return outputs;
        }
        

        List<Change_Control_Request_Line_Item__c> outputItems = new List<Change_Control_Request_Line_Item__c>();
        for (FundingBaseline__c baseline : baselines){
            if (initialItems?.get(baseline.Id) != null){
                Change_Control_Request_Line_Item__c item = initialItems.get(baseline.Id);
                item.Baseline_Measure_Description__c = baseline.Baseline_Version__c;
                item.Baseline_Measure_Description_Previous__c = baseline.Status__c;
                item.Cache__c = baseline.Total_Homes_to_be_Upgraded__c;
                outputItems.add(item);
            }else{
                Change_Control_Request_Line_Item__c item = new Change_Control_Request_Line_Item__c();
                item.Baseline__c = baseline.Id;
                item.Type__c = 'Phase Change';
                item.RecordTypeId = recordTypeId;
                item.Start_Date__c = baseline.Baseline_Start_Date__c;
                item.Start_Date_Previous__c = baseline.Baseline_Start_Date__c;
                item.End_Date__c = baseline.Baseline_End_Date__c;
                item.End_Date_Previous__c = baseline.Baseline_End_Date__c;
                item.Total_number_of_homes_to_be_upgraded__c = baseline.Total_Homes_to_be_Upgraded__c;
                item.Cache__c = baseline.Total_Homes_to_be_Upgraded__c;
                item.Baseline_Measure_Description__c = baseline.Baseline_Version__c;
                item.Baseline_Measure_Description_Previous__c = baseline.Status__c;
                outputItems.add(item);
            }
        }
        outputItems.addAll(newItems);
        output.items = outputItems;
        return outputs;
    } 


    public class Input{
        @InvocableVariable
        public List<FundingBaseline__c> baselines;
        @InvocableVariable
        public List<Change_Control_Request_Line_Item__c> items;

    }

    public class Output{
        @InvocableVariable
        public List<Change_Control_Request_Line_Item__c> items;
    }

}