force-app/main/default/objects/Change_Control_Request_Line_Item__c/Change_Control_Request_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Change Control Request Line Item</label>
    <nameField>
        <displayFormat>CRLIN-{000000}</displayFormat>
        <label>Change Control Request Line Item No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Change Control Request Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Change_Control_Request_Line_Item__c/fields/Co_funding_A_A_spend__c.field-meta.xml
<CustomField>
    <fullName>Co_funding_A_A_spend__c</fullName>
    <label>Co-Funding A&amp;A spend</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Change_Control_Request_Line_Item__c/fields/Co_Funding_A_A_spend_variance__c.field-meta.xml
<CustomField>
    <fullName>Co_Funding_A_A_spend_variance__c</fullName>
    <formula>Co_funding_A_A_spend__c -  Baseline__r.Baseline_Co_funding_A_A_spend__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Co-Funding A&amp;A spend variance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Change_Control_Request_Line_Item__c/fields/No_of_Homes_for_Off_Gas_grid_LCH_Uplift__c.field-meta.xml
<CustomField>
    <fullName>No_of_Homes_for_Off_Gas_grid_LCH_Uplift__c</fullName>
    <label>No. of Homes for Off Gas grid LCH Uplift</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Change_Control_Request_Line_Item__c/fields/No_of_Homes_for_On_Gas_grid_LCH_Uplift__c.field-meta.xml
<CustomField>
    <fullName>No_of_Homes_for_On_Gas_grid_LCH_Uplift__c</fullName>
    <label>No. of Homes for On Gas grid LCH Uplift</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Change_Control_Request_Line_Item__c/fields/Off_Gas_Variance__c.field-meta.xml
<CustomField>
    <fullName>Off_Gas_Variance__c</fullName>
    <formula>No_of_Homes_for_Off_Gas_grid_LCH_Uplift__c -  Baseline__r.No_of_Homes_for_Off_Gas_grid_LCH_Uplift__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Off Gas Variance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Change_Control_Request_Line_Item__c/fields/On_Gas_Variance__c.field-meta.xml
<CustomField>
    <fullName>On_Gas_Variance__c</fullName>
    <formula>No_of_Homes_for_On_Gas_grid_LCH_Uplift__c -  Baseline__r.No_of_Homes_for_On_Gas_grid_LCH_Offer__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>On Gas Variance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Change_Control_Request_Line_Item__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of record this change control request is for</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Award Baseline</fullName>
            </value>
            <value>
                <fullName>Sub Baseline</fullName>
            </value>
            <value>
                <fullName>Forecast</fullName>
            </value>
            <value>
                <fullName>Consortium Member Change</fullName>
            </value>
            <value>
                <fullName>Award Rename</fullName>
            </value>
            <value>
                <fullName>Grant Recipient Lead Change</fullName>
            </value>
            <value>
                <fullName>Measure Detail</fullName>
            </value>
            <value>
                <fullName>Supplier</fullName>
            </value>
            <value>
                <fullName>Project End Date</fullName>
            </value>
            <value>
                <fullName>Phase Change</fullName>
            </value>
            <value>
                <fullName>Income Verification</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Field_Audit__c/Field_Audit__c.object-meta.xml
<CustomObject>
    <description>Object for the auditing of field changes for Fraud and Error and Risk Register long text fields</description>
    <label>Field Audit</label>
    <nameField>
        <displayFormat>FA-{00000}</displayFormat>
        <label>Audit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Field Audits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Field_Audit__c/fields/Change_Date__c.field-meta.xml
<CustomField>
    <fullName>Change_Date__c</fullName>
    <label>Change Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Field_Audit__c/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <label>Field</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Audit__c/fields/Field_Data_Type__c.field-meta.xml
<CustomField>
    <fullName>Field_Data_Type__c</fullName>
    <label>Field Data Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Audit__c/fields/New_Value__c.field-meta.xml
<CustomField>
    <fullName>New_Value__c</fullName>
    <label>New Value</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Field_Audit__c/fields/Old_Value__c.field-meta.xml
<CustomField>
    <fullName>Old_Value__c</fullName>
    <label>Old Value</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Field_Audit__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <description>Soft lookup field to the changes parent record</description>
    <externalId>true</externalId>
    <label>Parent</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Audit__c/fields/Variance__c.field-meta.xml
<CustomField>
    <fullName>Variance__c</fullName>
    <label>Variance</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GmsCcrLineItemTriggerHandler.cls
public without sharing class GmsCcrLineItemTriggerHandler {
    
    public static final Map<String, String> fieldMapping = new Map<String, String>{
        'No_of_Homes_for_On_Gas_grid_LCH_Uplift__c'=>'On_Gas_Variance__c',
        'No_of_Homes_for_Off_Gas_grid_LCH_Uplift__c'=>'Off_Gas_Variance__c',
        'Co_funding_A_A_spend__c' => 'Co_Funding_A_A_spend_variance__c'
    };

    public static final List<String> typesToAction = new List<String>{'Award Baseline', 'Sub Baseline'};

    public static Map<String, Schema.SObjectField> fieldMap = Schema.Change_Control_Request_Line_Item__c.getSObjectType().getDescribe().fields.getMap();

    public static List<Change_Control_Request_Line_Item__c> onAfterInsert(
        List<Change_Control_Request_Line_Item__c> ccrlis
    ){
        List<Field_Audit__c> fieldChanges = buildFieldChanges(ccrlis);
        insert fieldChanges;
        return ccrlis;
    }

    public static List<Field_Audit__c> buildFieldChanges(List<Change_Control_Request_Line_Item__c> ccrlis){
        List<Field_Audit__c> fieldChanges = new List<Field_Audit__c>();
        for (Change_Control_Request_Line_Item__c item : ccrlis){
            if (typesToAction.contains(item.Type__c)){
                Map<String, Object> itemFields = item.getPopulatedFieldsAsMap();
                for (String fieldName : itemFields.keySet()){
                    if (!fieldName.contains('Variance') && !fieldName.contains('Previous_')){
                        Field_Audit__c change = sortFieldChange(itemFields, fieldName);
                        if (change != null){
                            fieldChanges.add(change);
                        }
                    }
                }
            }
        }
        return fieldChanges;
    }

    public static List<Change_Control_Request_Line_Item__c> onAfterUpdate(
        List<Change_Control_Request_Line_Item__c> newItems,
        Map<Id, Change_Control_Request_Line_Item__c> oldMap
    ){ 
        deleteFieldAudits(oldMap.keySet());
        List<Field_Audit__c> fieldChanges = buildFieldChanges(newItems);
        insert fieldChanges;
        return newItems;        
    }

    public static List<Field_Audit__c> onAfterDelete(
        Map<Id, Change_Control_Request_Line_Item__c> oldMap    
    ){
        return deleteFieldAudits(oldMap.keySet());
    }   

    public static List<Field_Audit__c> deleteFieldAudits(Set<Id> itemIds){
        List<Field_Audit__c> fieldAudits = [SELECT Id, Parent__c FROM Field_Audit__c WHERE Parent__c IN :itemIds];
        delete fieldAudits;
        return fieldAudits;
    }

    public static Field_Audit__c sortFieldChange(Map<String, Object> itemFields, String fieldName){
        Schema.DescribeFieldResult fieldDescribe = fieldMap?.get(fieldName.toLowerCase())?.getDescribe();
        if (fieldDescribe.isCalculated()){
            return null;
        }

        String varianceFieldName = fieldMapping?.get(fieldName);
        if (varianceFieldName == null){
            varianceFieldName = fieldName.removeEnd('__c');
            varianceFieldName += '_Variance__c';
        }

        if (itemFields.get('Type__c') == 'Forecast'){
            if (itemFields.get('Forecast_' + varianceFieldName) != null){
                varianceFieldName = 'Forecast_' + varianceFieldName;
            }
        }
        
        Decimal varianceValue = (Decimal)itemFields.get(varianceFieldName);
        if (varianceValue == null){
            return null;
        }
        if (varianceValue == 0){
            return null;
        }

        Field_Audit__c fieldChange = new Field_Audit__c();

        fieldChange.Variance__c = ((Decimal)itemFields.get(varianceFieldName)).format();
        fieldChange.Field_API_Name__c = fieldName;
        fieldChange.Change_Date__c = System.today();
        fieldChange.Field__c = fieldDescribe.getLabel() ?? 'No field name found';
        fieldChange.Field_Data_Type__c = String.valueOf(fieldDescribe.getType()) ?? 'No field type found';
        fieldChange.New_Value__c = getNewValue(itemFields.get(fieldName));
        fieldChange.Old_Value__c = getOldValue(itemFields.get(fieldName), itemFields.get(varianceFieldName));
        
        fieldChange.Parent__c = String.valueOf(itemFields.get('Id'));
        return fieldChange;
    }

    public static String getNewValue(Object fieldValue){
        if (fieldValue instanceOf Date){
            return ((Date)fieldValue).format();
        }else if (fieldValue instanceOf Decimal){
            return ((Decimal)fieldValue).format();
        }else{
            return String.valueOf(fieldValue);
        }
    }

    public static String getOldValue(Object fieldValue, Object varianceValue){
        if (fieldValue instanceOf Date){
            Date oldDate = (Date)fieldValue;
            oldDate.addDays(Math.round(-1*(Decimal)varianceValue));
            return oldDate.format();
        }
        // assume its a decimal if we get here 
        return ((Decimal)fieldValue - (Decimal)varianceValue).format();
    }
}