force-app/main/default/objects/Change_Control_Request_Line_Item__c/Change_Control_Request_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Change Control Request Line Item</label>
    <nameField>
        <displayFormat>CRLIN-{000000}</displayFormat>
        <label>Change Control Request Line Item No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Change Control Request Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Change_Control_Request_Line_Item__c/fields/Baseline__c.field-meta.xml
<CustomField>
    <fullName>Baseline__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Baseline</label>
    <referenceTo>FundingBaseline__c</referenceTo>
    <relationshipLabel>Change Control Request Line Items</relationshipLabel>
    <relationshipName>Change_Control_Request_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Change_Control_Request_Line_Item__c/fields/Change_Control_Request__c.field-meta.xml
<CustomField>
    <fullName>Change_Control_Request__c</fullName>
    <label>Change Control Request</label>
    <referenceTo>FundingAwardAmendment</referenceTo>
    <relationshipLabel>Change Control Request Line Items</relationshipLabel>
    <relationshipName>Change_Control_Request_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Change_Control_Request_Line_Item__c/fields/Grant_A_A_Spend__c.field-meta.xml
<CustomField>
    <fullName>Grant_A_A_Spend__c</fullName>
    <label>Grant A&amp;A Spend</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Change_Control_Request_Line_Item__c/fields/Grant_A_A_Spend_Variance__c.field-meta.xml
<CustomField>
    <fullName>Grant_A_A_Spend_Variance__c</fullName>
    <formula>Grant_A_A_Spend__c  -  Baseline__r.Baseline_Grant_A_A_Spend__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Grant A&amp;A Spend Variance</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Change_Control_Request_Line_Item__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of record this change control request is for</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Award Baseline</fullName>
            </value>
            <value>
                <fullName>Sub Baseline</fullName>
            </value>
            <value>
                <fullName>Forecast</fullName>
            </value>
            <value>
                <fullName>Consortium Member Change</fullName>
            </value>
            <value>
                <fullName>Award Rename</fullName>
            </value>
            <value>
                <fullName>Grant Recipient Lead Change</fullName>
            </value>
            <value>
                <fullName>Measure Detail</fullName>
            </value>
            <value>
                <fullName>Supplier</fullName>
            </value>
            <value>
                <fullName>Project End Date</fullName>
            </value>
            <value>
                <fullName>Phase Change</fullName>
            </value>
            <value>
                <fullName>Income Verification</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Field_Audit__c/Field_Audit__c.object-meta.xml
<CustomObject>
    <description>Object for the auditing of field changes for Fraud and Error and Risk Register long text fields</description>
    <label>Field Audit</label>
    <nameField>
        <displayFormat>FA-{00000}</displayFormat>
        <label>Audit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Field Audits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Field_Audit__c/fields/New_Value__c.field-meta.xml
<CustomField>
    <fullName>New_Value__c</fullName>
    <label>New Value</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Field_Audit__c/fields/Old_Value__c.field-meta.xml
<CustomField>
    <fullName>Old_Value__c</fullName>
    <label>Old Value</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Field_Audit__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <description>Soft lookup field to the changes parent record</description>
    <externalId>true</externalId>
    <label>Parent</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FundingBaseline__c/FundingBaseline__c.object-meta.xml
<CustomObject>
    <description>Object to store initial and revised KPIs for specific time periods for Funding Awards</description>
    <label>Baseline</label>
    <nameField>
        <displayFormat>BAS-{0000}</displayFormat>
        <label>Funding Baseline Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Baselines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FundingBaseline__c/fields/Funding_Award__c.field-meta.xml
<CustomField>
    <fullName>Funding_Award__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Master Detail Relationship to parent Award</description>
    <label>Funding Award</label>
    <referenceTo>FundingAward</referenceTo>
    <relationshipLabel>Baselines</relationshipLabel>
    <relationshipName>Funding_Baselines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/GmsCcrLineItemTriggerHandler_Test.cls
@istest
public with sharing class GmsCcrLineItemTriggerHandler_Test {
    
    @TestSetup
    static void makeData(){
        FundingAward fa = new FundingAward();
        insert fa;

        FundingBaseline__c fb = new FundingBaseline__c();
        fb.Funding_Award__c = fa.Id;
        insert fb;

        FundingAwardAmendment faa = new FundingAwardAmendment(FundingAwardId = fa.Id);
        insert faa;

        Change_Control_Request_Line_Item__c ccrli1 = new Change_Control_Request_Line_Item__c(Change_Control_Request__c = faa.Id);
        ccrli1.Grant_A_A_Spend__c = 15;
        ccrli1.Type__c = 'Sub Baseline';
        ccrli1.Baseline__c = fb.Id;

        Change_Control_Request_Line_Item__c ccrli2 = new Change_Control_Request_Line_Item__c(Change_Control_Request__c = faa.Id);
        ccrli2.Grant_A_A_Spend__c = 15;
        ccrli2.Type__c = 'Sub Baseline';
        ccrli2.Baseline__c = fb.Id;
        List<Change_Control_Request_Line_Item__c> ccrlis = new List<Change_Control_Request_Line_Item__c>{ccrli1, ccrli2};
        insert ccrlis;
    }
    
    @istest
    public static void onAfterInsert(){
        // quick (to write) basic tests 
        FundingAwardAmendment faa = [SELECT Id FROM FundingAwardAmendment LIMIT 1];
        Change_Control_Request_Line_Item__c ccrli = new Change_Control_Request_Line_Item__c(Change_Control_Request__c = faa.Id);
        ccrli.Grant_A_A_Spend__c = 15;
        ccrli.Type__c = 'Sub Baseline';
        Test.startTest();
        insert ccrli;
        Test.stopTest();
        List<Field_Audit__c> changes = [SELECT Id, New_Value__c, Old_Value__c FROM Field_Audit__c WHERE Parent__c = :ccrli.Id];
        Assert.areEqual(15, Integer.valueOf(changes[0].New_Value__c), 'Field Audits new value');
        Assert.areEqual(0, Integer.valueOf(changes[0].Old_Value__c), 'Field Audits new value');
    }

    @istest
    public static void onAfterUpdate(){
        Change_Control_Request_Line_Item__c ccrli = [SELECT Id, Grant_A_A_Spend__c, Grant_A_A_Spend_Variance__c FROM Change_Control_Request_Line_Item__c LIMIT 1];
        ccrli.Grant_A_A_Spend__c = 20;
        Test.startTest();
        update ccrli;
        Test.stopTest();
        List<Field_Audit__c> changes = [SELECT Id, New_Value__c, Old_Value__c FROM Field_Audit__c WHERE Parent__c = :ccrli.Id];
    
        Assert.areEqual(1, changes.size(), 'the number of field audit records');
        Assert.areEqual(20, Integer.valueOf(changes[0].New_Value__c), 'Field Audits new value');
    }

    @istest
    public static void onAfterDelete(){
        Change_Control_Request_Line_Item__c ccrli = [SELECT Id, Grant_A_A_Spend__c, Grant_A_A_Spend_Variance__c FROM Change_Control_Request_Line_Item__c LIMIT 1];
        Test.startTest();
        delete ccrli;
        Test.stopTest();
        List<Field_Audit__c> changes = [SELECT Id, New_Value__c, Old_Value__c FROM Field_Audit__c WHERE Parent__c = :ccrli.Id];
    
        Assert.areEqual(0, changes.size(), 'the number of field audit records');
    }
}