force-app/main/default/objects/BaselineMeasureDetail__c/BaselineMeasureDetail__c.object-meta.xml
<CustomObject>
    <description>Headline number for each measure included in the phase: EWI, CWI, Underfloor insulation, Loft insulation, Draught proofing, ASHP, GSHP, SGL, Storage heaters*(TBC), Solar PV, Solar Thermal, Windows, Ventilation, Other</description>
    <label>Baseline Measure Detail</label>
    <nameField>
        <displayFormat>MSD-{000000}</displayFormat>
        <label>Measure Detail Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Baseline Measure Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BaselineMeasureDetail__c/fields/Funding_Award__c.field-meta.xml
<CustomField>
    <fullName>Funding_Award__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Funding Award</label>
    <referenceTo>FundingAward</referenceTo>
    <relationshipLabel>Baseline Measure Detail</relationshipLabel>
    <relationshipName>Baseline_Measure_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BaselineMeasureDetail__c/fields/Funding_Baseline__c.field-meta.xml
<CustomField>
    <fullName>Funding_Baseline__c</fullName>
    <label>Funding Baseline</label>
    <referenceTo>FundingBaseline__c</referenceTo>
    <relationshipLabel>Baseline Measure Detail (Funding Baseline)</relationshipLabel>
    <relationshipName>Baseline_Measure_Types</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BaselineMeasureDetail__c/fields/Measure_KPI_Number__c.field-meta.xml
<CustomField>
    <fullName>Measure_KPI_Number__c</fullName>
    <description>KPI that has a numerical value</description>
    <label>Measure KPI (Number)</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BaselineMeasureDetail__c/fields/Measure_Type__c.field-meta.xml
<CustomField>
    <fullName>Measure_Type__c</fullName>
    <description>Depreciated - Predefined list of measure types</description>
    <label>Measure Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Property_Measure_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/BaselineMeasureDetail__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Historic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Change_Control_Request_Line_Item__c/Change_Control_Request_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Change Control Request Line Item</label>
    <nameField>
        <displayFormat>CRLIN-{000000}</displayFormat>
        <label>Change Control Request Line Item No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Change Control Request Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Change_Control_Request_Line_Item__c/fields/Baseline_Measure_Detail__c.field-meta.xml
<CustomField>
    <fullName>Baseline_Measure_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Baseline Measure Detail</label>
    <referenceTo>BaselineMeasureDetail__c</referenceTo>
    <relationshipLabel>Change Control Request Line Items</relationshipLabel>
    <relationshipName>Change_Control_Request_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Change_Control_Request_Line_Item__c/fields/Measure_KPI_Number__c.field-meta.xml
<CustomField>
    <fullName>Measure_KPI_Number__c</fullName>
    <description>KPI that has a numerical value</description>
    <label>Measure KPI (Number)</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Change_Control_Request_Line_Item__c/fields/Measure_Type__c.field-meta.xml
<CustomField>
    <fullName>Measure_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Populated from the change request form when a change involves a measure detail change. The value will mirror the type field on related baseline mirror object.</description>
    <label>Property Measure Type</label>
    <referenceTo>PropertyMeasureType__c</referenceTo>
    <relationshipLabel>Change Control Request Line Items</relationshipLabel>
    <relationshipName>Change_Control_Request_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FundingAwardAmendment/fields/Phase_Baseline__c.field-meta.xml
<CustomField>
    <fullName>Phase_Baseline__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent Baseline of change control record - Phase for phase requests and Award for change control</description>
    <label>Baseline</label>
    <referenceTo>FundingBaseline__c</referenceTo>
    <relationshipLabel>Change Control Request</relationshipLabel>
    <relationshipName>Change_Control_Request</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FundingBaseline__c/FundingBaseline__c.object-meta.xml
<CustomObject>
    <description>Object to store initial and revised KPIs for specific time periods for Funding Awards</description>
    <label>Baseline</label>
    <nameField>
        <displayFormat>BAS-{0000}</displayFormat>
        <label>Funding Baseline Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Baselines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FundingBaseline__c/fields/Baseline_Type__c.field-meta.xml
<CustomField>
    <fullName>Baseline_Type__c</fullName>
    <label>Baseline Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Award</fullName>
            </value>
            <value>
                <fullName>Phase</fullName>
            </value>
            <value>
                <fullName>Financial Year</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FundingBaseline__c/fields/Funding_Award__c.field-meta.xml
<CustomField>
    <fullName>Funding_Award__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Master Detail Relationship to parent Award</description>
    <label>Funding Award</label>
    <referenceTo>FundingAward</referenceTo>
    <relationshipLabel>Baselines</relationshipLabel>
    <relationshipName>Funding_Baselines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FundingBaseline__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Historic</fullName>
            </value>
            <value>
                <fullName>Pending Submission</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Milestones Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PropertyMeasureType__c/PropertyMeasureType__c.object-meta.xml
<CustomObject>
    <description>Specifies a list of Property Measure Types and related data</description>
    <label>Property Measure Type</label>
    <nameField>
        <label>Measure Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Property Measure Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PropertyMeasureType__c/fields/Cost_Cap_Category__c.field-meta.xml
<CustomField>
    <fullName>Cost_Cap_Category__c</fullName>
    <description>ABS Cost Cap Category</description>
    <inlineHelpText>ABS Cost Cap Category</inlineHelpText>
    <label>Cost Cap Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Energy Performance</fullName>
            </value>
            <value>
                <fullName>Low Carbon Heat</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PropertyMeasureType__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Used in the BatchMeasureMix apex Class</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Historic</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>DESNZ Approved</fullName>
            </value>
            <value>
                <fullName>Custom Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PropertyMeasureType__c/recordTypes/DESNZ.recordType-meta.xml
<RecordType>
    <fullName>DESNZ</fullName>
    <active>true</active>
    <label>DESNZ</label>
</RecordType>

force-app/main/default/globalValueSets/Property_Measure_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>External Wall Insulation</fullName>
    </customValue>
    <customValue>
        <fullName>Cavity Wall Insulation</fullName>
    </customValue>
    <customValue>
        <fullName>Underfloor insulation</fullName>
    </customValue>
    <customValue>
        <fullName>Loft insulation</fullName>
    </customValue>
    <customValue>
        <fullName>Draughtproofing</fullName>
    </customValue>
    <customValue>
        <fullName>Air Source Heat Pump</fullName>
    </customValue>
    <customValue>
        <fullName>Ground Source Heat Pump</fullName>
    </customValue>
    <customValue>
        <fullName>Secondary Glazing</fullName>
    </customValue>
    <customValue>
        <fullName>Storage heaters*(TBC)</fullName>
    </customValue>
    <customValue>
        <fullName>Solar PV</fullName>
    </customValue>
    <customValue>
        <fullName>Solar Thermal</fullName>
    </customValue>
    <customValue>
        <fullName>Windows</fullName>
    </customValue>
    <customValue>
        <fullName>Ventilation</fullName>
    </customValue>
    <customValue>
        <fullName>Wet Central Heating</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Additional Capital Expenditure</fullName>
    </customValue>
    <customValue>
        <fullName>Double Glazing</fullName>
    </customValue>
    <customValue>
        <fullName>High heat retention storage heaters</fullName>
    </customValue>
    <customValue>
        <fullName>Shared Ground loops</fullName>
    </customValue>
    <masterLabel>Property Measure Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/GmsCCRFormBaselineMeasure_Test.cls
@isTest
public class GmsCCRFormBaselineMeasure_Test {
    @isTest
    public static void convertBaselineMeasure() {
        // create test data
        GmsCCRFormBaselineMeasure.FlowInputs inputs = createData();

        Test.startTest();
        List<GmsCCRFormBaselineMeasure.FlowOutputs> results = GmsCCRFormBaselineMeasure.convertBaselineMeasure(
            new List<GmsCCRFormBaselineMeasure.FlowInputs>{inputs}
        );
        Test.stopTest();
        
        // Verify results
        Assert.areEqual(1, results.size(), 'Number of results');
        Assert.areEqual(3, results[0].lineItemsOutput.size(), 'Number of line items');
        //Assert.areEquals(2, results[0].lineItemsOutput.size());
    }

    @istest
    public static void convertBaselineMeasure_NoBaselineMeasureDetails(){
        GmsCCRFormBaselineMeasure.FlowInputs inputs = createData();
        inputs.measureDetails = null;

        Test.startTest();
        List<GmsCCRFormBaselineMeasure.FlowOutputs> results = GmsCCRFormBaselineMeasure.convertBaselineMeasure(
            new List<GmsCCRFormBaselineMeasure.FlowInputs>{inputs}
        );
        Test.stopTest();

        Assert.areEqual(1, results.size(), 'Number of results');
        Assert.areEqual(1, results[0].lineItemsOutput.size(), 'Number of line items');
    }

    @istest
    public static void convertBaselineMeasure_NoLineItems(){
        GmsCCRFormBaselineMeasure.FlowInputs inputs = createData();
        inputs.lineItems = null;

        Test.startTest();
        List<GmsCCRFormBaselineMeasure.FlowOutputs> results = GmsCCRFormBaselineMeasure.convertBaselineMeasure(
            new List<GmsCCRFormBaselineMeasure.FlowInputs>{inputs}
        );
        Test.stopTest();

        Assert.areEqual(1, results.size(), 'Number of results');
        Assert.areEqual(2, results[0].lineItemsOutput.size(), 'Number of line items');
    }

    public static GmsCCRFormBaselineMeasure.FlowInputs createData(){
        // Create test data, no need to insert as the code doesn't touch the database
        FundingAward fa1 = new FundingAward();
        
        //Create Baseline Measure Type
        PropertyMeasureType__c propertyMeasureType = new PropertyMeasureType__c(
            Name = 'External Wall Insulation',
            Status__c = 'DESNZ Approved',
            Cost_Cap_Category__c = 'Energy Performance'
        );
        insert propertyMeasureType;
        
        PropertyMeasureType__c propertyMeasureType1 = new PropertyMeasureType__c(
            Name = 'External Wall Insulation',
            Status__c = 'DESNZ Approved',
            Cost_Cap_Category__c = 'Energy Performance'
        );
        insert propertyMeasureType1;

        
        FundingBaseline__c phaseBaseline1 = new FundingBaseline__c(
            Baseline_Type__c = 'Phase', 
            Funding_Award__c = fa1.Id, 
            Status__c = 'Active'
        );

        BaselineMeasureDetail__c bmd1 = new BaselineMeasureDetail__c(
            Measure_KPI_Number__c = 100.0,
            Measure_Type__c = propertyMeasureType.Id,
            Description__c = 'Test Description 1',
            Funding_Baseline__c = phaseBaseline1.Id
        );
        
        BaselineMeasureDetail__c bmd2 = new BaselineMeasureDetail__c(
            Measure_KPI_Number__c = 200.0,
            Measure_Type__c = 'propertyMeasureType1',
            Description__c = 'Test Description 2',
            Funding_Baseline__c = phaseBaseline1.Id
        );

        FundingAwardAmendment ccr = new FundingAwardAmendment(
            Phase_Baseline__c = phaseBaseline1.Id,
            FundingAwardId = fa1.Id
        );

        Change_Control_Request_Line_Item__c ccr1 = new Change_Control_Request_Line_Item__c(
            Baseline_Measure_Detail__c = bmd1.Id,
            Measure_KPI_Number__c = 150.0
        );
        
        GmsCCRFormBaselineMeasure.FlowInputs inputs = new GmsCCRFormBaselineMeasure.FlowInputs();
        inputs.lineItems = new List<Change_Control_Request_Line_Item__c>{ccr1};
        inputs.measureDetails = new List<BaselineMeasureDetail__c>{bmd1, bmd2};
        return inputs;
    }
}