force-app/main/default/objects/BaselineMeasureDetail__c/BaselineMeasureDetail__c.object-meta.xml
<CustomObject>
    <description>Headline number for each measure included in the phase: EWI, CWI, Underfloor insulation, Loft insulation, Draught proofing, ASHP, GSHP, SGL, Storage heaters*(TBC), Solar PV, Solar Thermal, Windows, Ventilation, Other</description>
    <label>Baseline Measure Detail</label>
    <nameField>
        <displayFormat>MSD-{000000}</displayFormat>
        <label>Measure Detail Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Baseline Measure Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BaselineMeasureDetail__c/fields/Cost_to_install_measure__c.field-meta.xml
<CustomField>
    <fullName>Cost_to_install_measure__c</fullName>
    <inlineHelpText>The figures entered into the &apos;Cost to install measure&apos; column should be best estimate averages, and the costs listed for this question are for information only, rather than forming part of the detailed baseline for this phase of the project.</inlineHelpText>
    <label>Cost to install measure</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/BaselineMeasureDetail__c/fields/Measure_KPI_Number__c.field-meta.xml
<CustomField>
    <fullName>Measure_KPI_Number__c</fullName>
    <description>KPI that has a numerical value</description>
    <label>Measure KPI (Number)</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BaselineMeasureDetail__c/fields/Measure_Type__c.field-meta.xml
<CustomField>
    <fullName>Measure_Type__c</fullName>
    <description>Depreciated - Predefined list of measure types</description>
    <label>Measure Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Property_Measure_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/BaselineMeasureDetail__c/fields/Property_Measure_Type__c.field-meta.xml
<CustomField>
    <fullName>Property_Measure_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property Measure Type</label>
    <referenceTo>PropertyMeasureType__c</referenceTo>
    <relationshipLabel>Baseline Measure Detail</relationshipLabel>
    <relationshipName>Property_Measure_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Change_Control_Request_Line_Item__c/Change_Control_Request_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Change Control Request Line Item</label>
    <nameField>
        <displayFormat>CRLIN-{000000}</displayFormat>
        <label>Change Control Request Line Item No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Change Control Request Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Change_Control_Request_Line_Item__c/fields/Baseline_Measure_Description__c.field-meta.xml
<CustomField>
    <fullName>Baseline_Measure_Description__c</fullName>
    <description>Populated from CCR form and will be a mirror of the related baseline measure records description.</description>
    <label>Baseline Measure Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Change_Control_Request_Line_Item__c/fields/Baseline_Measure_Detail__c.field-meta.xml
<CustomField>
    <fullName>Baseline_Measure_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Baseline Measure Detail</label>
    <referenceTo>BaselineMeasureDetail__c</referenceTo>
    <relationshipLabel>Change Control Request Line Items</relationshipLabel>
    <relationshipName>Change_Control_Request_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Change_Control_Request_Line_Item__c/fields/Cost_To_Install_Measure__c.field-meta.xml
<CustomField>
    <fullName>Cost_To_Install_Measure__c</fullName>
    <label>Cost To Install Measure</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Change_Control_Request_Line_Item__c/fields/Measure_KPI_Number__c.field-meta.xml
<CustomField>
    <fullName>Measure_KPI_Number__c</fullName>
    <description>KPI that has a numerical value</description>
    <label>Measure KPI (Number)</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Change_Control_Request_Line_Item__c/fields/Measure_Type__c.field-meta.xml
<CustomField>
    <fullName>Measure_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Populated from the change request form when a change involves a measure detail change. The value will mirror the type field on related baseline mirror object.</description>
    <label>Property Measure Type</label>
    <referenceTo>PropertyMeasureType__c</referenceTo>
    <relationshipLabel>Change Control Request Line Items</relationshipLabel>
    <relationshipName>Change_Control_Request_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Change_Control_Request_Line_Item__c/fields/Previous_Cost_To_Install_Measure__c.field-meta.xml
<CustomField>
    <fullName>Previous_Cost_To_Install_Measure__c</fullName>
    <label>Previous Cost To Install Measure</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Change_Control_Request_Line_Item__c/fields/Previous_Measure_KPI_Number__c.field-meta.xml
<CustomField>
    <fullName>Previous_Measure_KPI_Number__c</fullName>
    <description>KPI value prior to the change control request</description>
    <label>Measure KPI (Previous)</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Change_Control_Request_Line_Item__c/fields/Property_Measure_Type__c.field-meta.xml
<CustomField>
    <fullName>Property_Measure_Type__c</fullName>
    <description>Populated from the change request form when a change involves a measure detail change. The value will mirror the type field on related baseline mirror object.</description>
    <label>Measure Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Property_Measure_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Property_Measure_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>External Wall Insulation</fullName>
    </customValue>
    <customValue>
        <fullName>Cavity Wall Insulation</fullName>
    </customValue>
    <customValue>
        <fullName>Underfloor insulation</fullName>
    </customValue>
    <customValue>
        <fullName>Loft insulation</fullName>
    </customValue>
    <customValue>
        <fullName>Draughtproofing</fullName>
    </customValue>
    <customValue>
        <fullName>Air Source Heat Pump</fullName>
    </customValue>
    <customValue>
        <fullName>Ground Source Heat Pump</fullName>
    </customValue>
    <customValue>
        <fullName>Secondary Glazing</fullName>
    </customValue>
    <customValue>
        <fullName>Storage heaters*(TBC)</fullName>
    </customValue>
    <customValue>
        <fullName>Solar PV</fullName>
    </customValue>
    <customValue>
        <fullName>Solar Thermal</fullName>
    </customValue>
    <customValue>
        <fullName>Windows</fullName>
    </customValue>
    <customValue>
        <fullName>Ventilation</fullName>
    </customValue>
    <customValue>
        <fullName>Wet Central Heating</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Additional Capital Expenditure</fullName>
    </customValue>
    <customValue>
        <fullName>Double Glazing</fullName>
    </customValue>
    <customValue>
        <fullName>High heat retention storage heaters</fullName>
    </customValue>
    <customValue>
        <fullName>Shared Ground loops</fullName>
    </customValue>
    <masterLabel>Property Measure Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/GmsCCRFormBaselineMeasure.cls
public without sharing class GmsCCRFormBaselineMeasure {
    
    @InvocableMethod(label='Baseline Measure Convert to CCF')
    public static List<FlowOutputs> convertBaselineMeasure(List<FlowInputs> inputs) {
        FlowOutputs result = new FlowOutputs();
        List<FlowOutputs> resultList = new List<FlowOutputs>{result};
        List<Change_Control_Request_Line_Item__c> ccrUpdate = new List<Change_Control_Request_Line_Item__c>();

        Map<Id,Change_Control_Request_Line_Item__c> ccrMap = new Map<Id,Change_Control_Request_Line_Item__c>();
        List<Change_Control_Request_Line_Item__c> newLineItems = new List<Change_Control_Request_Line_Item__c>();

        if(inputs?.get(0)?.lineItems != null) {
        	for(Change_Control_Request_Line_Item__c ccrs : inputs.get(0).lineItems) {
                if (ccrs.Baseline_Measure_Detail__c == null){
                    newLineItems.add(ccrs);
                }else{
                    ccrMap.put(ccrs.Baseline_Measure_Detail__c, ccrs);
                }
            }
        }

        if (inputs?.get(0)?.measureDetails != null){
            for(BaselineMeasureDetail__c bmd : inputs.get(0).measureDetails){
                Change_Control_Request_Line_Item__c item = new Change_Control_Request_Line_Item__c();
                if(ccrMap.containsKey(bmd.Id)) {
                    item.Measure_KPI_Number__c = ccrMap.get(bmd.Id).Measure_KPI_Number__c;
                    item.Measure_Type__c = ccrMap.get(bmd.Id).Measure_Type__c;
                    item.Baseline_Measure_Description__c = ccrMap.get(bmd.Id).Baseline_Measure_Description__c;
                    item.Cost_To_Install_Measure__c = ccrMap.get(bmd.Id).Cost_To_Install_Measure__c;
                } else {
                    item.Measure_KPI_Number__c = bmd.Measure_KPI_Number__c;
                    item.Measure_Type__c = bmd.Property_Measure_Type__c;
                    item.Baseline_Measure_Description__c = bmd.Description__c;
                    item.Cost_To_Install_Measure__c = bmd.Cost_to_install_measure__c;
                }
                item.Previous_Measure_KPI_Number__c = bmd.Measure_KPI_Number__c;
                item.Previous_Cost_To_Install_Measure__c = bmd.Cost_to_install_measure__c;
                item.Baseline_Measure_Detail__c = bmd.Id;

                ccrUpdate.add(item);
            }
        }

        if(newLineItems.size() > 0){
            ccrUpdate.addAll(newLineItems);
        }

        result.lineItemsOutput = ccrUpdate;
        return resultList;
    }
    
    public class FlowInputs{
        
    	@InvocableVariable
    	public List<BaselineMeasureDetail__c> measureDetails;
        
    	@InvocableVariable
    	public List<Change_Control_Request_Line_Item__c> lineItems;
    
    }
    
    public class FlowOutputs{
      	
        @InvocableVariable
        public List<Change_Control_Request_Line_Item__c> lineItemsOutput;
    
    }

}