force-app/main/default/objects/BaselineMeasureDetail__c/BaselineMeasureDetail__c.object-meta.xml
<CustomObject>
    <description>Headline number for each measure included in the phase: EWI, CWI, Underfloor insulation, Loft insulation, Draught proofing, ASHP, GSHP, SGL, Storage heaters*(TBC), Solar PV, Solar Thermal, Windows, Ventilation, Other</description>
    <label>Baseline Measure Detail</label>
    <nameField>
        <displayFormat>MSD-{000000}</displayFormat>
        <label>Measure Detail Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Baseline Measure Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BaselineMeasureDetail__c/fields/Baseline__c.field-meta.xml
<CustomField>
    <fullName>Baseline__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Baseline</label>
    <referenceTo>FundingBaseline__c</referenceTo>
    <relationshipLabel>Baseline Measure Detail (Baseline)</relationshipLabel>
    <relationshipName>Baseline_Measure_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BaselineMeasureDetail__c/fields/Funding_Baseline__c.field-meta.xml
<CustomField>
    <fullName>Funding_Baseline__c</fullName>
    <label>Funding Baseline</label>
    <referenceTo>FundingBaseline__c</referenceTo>
    <relationshipLabel>Baseline Measure Detail (Funding Baseline)</relationshipLabel>
    <relationshipName>Baseline_Measure_Types</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BaselineMeasureDetail__c/fields/Measure_KPI_Number__c.field-meta.xml
<CustomField>
    <fullName>Measure_KPI_Number__c</fullName>
    <description>KPI that has a numerical value</description>
    <label>Measure KPI (Number)</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BaselineMeasureDetail__c/fields/Property_Measure_Type__c.field-meta.xml
<CustomField>
    <fullName>Property_Measure_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property Measure Type</label>
    <referenceTo>PropertyMeasureType__c</referenceTo>
    <relationshipLabel>Baseline Measure Detail</relationshipLabel>
    <relationshipName>Property_Measure_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Funding_Award_Milestone__c/Funding_Award_Milestone__c.object-meta.xml
<CustomObject>
    <label>Funding Award Milestone</label>
    <nameField>
        <displayFormat>FAM-{00000}</displayFormat>
        <label>Funding Award Milestone Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funding Award Milestones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Funding_Award_Milestone__c/fields/Parent_Baseline__c.field-meta.xml
<CustomField>
    <fullName>Parent_Baseline__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Baseline</label>
    <referenceTo>FundingBaseline__c</referenceTo>
    <relationshipLabel>Funding Award Milestones</relationshipLabel>
    <relationshipName>Funding_Award_Milestones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Funding_Award_Milestone_Measure__c/Funding_Award_Milestone_Measure__c.object-meta.xml
<CustomObject>
    <description>Number of Individual Measures associated with a challenge fund milestone record</description>
    <label>Funding Award Milestone Measure</label>
    <nameField>
        <displayFormat>FAMM-{00000}</displayFormat>
        <label>Funding Award Milestone Measure Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funding Award Milestone Measures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Funding_Award_Milestone_Measure__c/fields/Funding_Award_Milestone__c.field-meta.xml
<CustomField>
    <fullName>Funding_Award_Milestone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Funding Award Milestone</label>
    <referenceTo>Funding_Award_Milestone__c</referenceTo>
    <relationshipLabel>Funding Award Milestone Measures</relationshipLabel>
    <relationshipName>Related_Milestone_Measures</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Funding_Award_Milestone_Measure__c/fields/Installed_Measure_Count__c.field-meta.xml
<CustomField>
    <fullName>Installed_Measure_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Number of the measure type that has been installed, that have been reported against the baseline from Trustmark and synced to salesforce as property measures</inlineHelpText>
    <label>Installed Measure Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Funding_Award_Milestone_Measure__c/fields/Property_Measure_Type__c.field-meta.xml
<CustomField>
    <fullName>Property_Measure_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property Measure Type</label>
    <referenceTo>PropertyMeasureType__c</referenceTo>
    <relationshipLabel>Funding Award Milestone Measures</relationshipLabel>
    <relationshipName>Funding_Award_Milestone_Measures</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Funding_Award_Milestone_Measure__c/fields/Target_Measure_Count__c.field-meta.xml
<CustomField>
    <fullName>Target_Measure_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Populated from the parent baselines, baseline measure detail at the time of milestone creation</inlineHelpText>
    <label>Target Measure Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FundingPropertyDetail__c/FundingPropertyDetail__c.object-meta.xml
<CustomObject>
    <description>Details of relevant property including number of rooms etc. Used as to store details for properties as they relate to the award rather than general address details</description>
    <label>Funding Property Detail</label>
    <nameField>
        <displayFormat>PTY-{000000}</displayFormat>
        <label>Funding Property Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funding Property Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FundingPropertyDetail__c/fields/Baseline__c.field-meta.xml
<CustomField>
    <fullName>Baseline__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Baseline that this property has been allocated to</description>
    <label>Baseline</label>
    <referenceTo>FundingBaseline__c</referenceTo>
    <relationshipLabel>Property Details</relationshipLabel>
    <relationshipName>Funding_Property_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property_Measure__c/Property_Measure__c.object-meta.xml
<CustomObject>
    <description>Details of the work to apply a measure type to a property</description>
    <label>Property Measure</label>
    <nameField>
        <displayFormat>PRM-{00000}</displayFormat>
        <label>Property Measure Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Property Measures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Property_Measure__c/fields/Measure_Type_Parent__c.field-meta.xml
<CustomField>
    <fullName>Measure_Type_Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Lookup to the Measure type Parent</inlineHelpText>
    <label>Measure Type Parent</label>
    <referenceTo>PropertyMeasureType__c</referenceTo>
    <relationshipLabel>Property Measure Parents</relationshipLabel>
    <relationshipName>Measure_Type_Parents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property_Measure__c/fields/Property_Detail__c.field-meta.xml
<CustomField>
    <fullName>Property_Detail__c</fullName>
    <label>Property Detail</label>
    <referenceTo>FundingPropertyDetail__c</referenceTo>
    <relationshipLabel>Property Measures</relationshipLabel>
    <relationshipName>Scheme_Measures</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/GmsMilestoneTriggerHandler.cls
public without sharing class GmsMilestoneTriggerHandler {

    public static void onAfterInsert(List<Funding_Award_Milestone__c> milestones){
        Map<Id, Funding_Award_Milestone__c> baselineIds = new Map<Id, Funding_Award_Milestone__c>();
        for (Funding_Award_Milestone__c milestone : milestones){
            baselineIds.put(milestone.Parent_Baseline__c, milestone);
        }
        
        Map<String, Decimal> installedMeasureCounts = new Map<String, Decimal>();
        List<AggregateResult> ags = [SELECT COUNT(Id) measureCount, Measure_Type_Parent__c type, Property_Detail__r.Baseline__c baseline FROM Property_Measure__c WHERE Property_Detail__r.Baseline__c IN :baselineIds.keySet() GROUP BY CUBE(Measure_Type_Parent__c, Property_Detail__r.Baseline__c)];
        for (AggregateResult ag :ags){
            installedMeasureCounts.put((String)ag.get('type') + (String)ag.get('baseline') ,(Decimal)ag.get('measureCount'));
        }

        List<BaselineMeasureDetail__c> bmds = [SELECT Id, Property_Measure_Type__c, Measure_KPI_Number__c, Funding_Baseline__c FROM BaselineMeasureDetail__c WHERE Funding_Baseline__c = :baselineIds.keySet()];
        
        // create the new milestone measure records based on baseline measure details 
        List<Funding_Award_Milestone_Measure__c> famms = new List<Funding_Award_Milestone_Measure__c>();
        for (BaselineMeasureDetail__c bmd : bmds){
            Funding_Award_Milestone_Measure__c famm = new Funding_Award_Milestone_Measure__c(
                Funding_Award_Milestone__c = baselineIds.get(bmd.Funding_Baseline__c).Id,
                Property_Measure_Type__c = bmd.Property_Measure_Type__c,
                Target_Measure_Count__c = bmd.Measure_KPI_Number__c,
                Installed_Measure_Count__c = installedMeasureCounts.get((String)bmd.Property_Measure_Type__c + (String)bmd.Funding_Baseline__c) ?? 0
            );
            famms.add(famm);
        }

        insert famms;
    }
}