force-app/main/default/objects/BaselineMeasureDetail__c/BaselineMeasureDetail__c.object-meta.xml
<CustomObject>
    <description>Headline number for each measure included in the phase: EWI, CWI, Underfloor insulation, Loft insulation, Draught proofing, ASHP, GSHP, SGL, Storage heaters*(TBC), Solar PV, Solar Thermal, Windows, Ventilation, Other</description>
    <label>Baseline Measure Detail</label>
    <nameField>
        <displayFormat>MSD-{000000}</displayFormat>
        <label>Measure Detail Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Baseline Measure Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BaselineMeasureDetail__c/fields/Baseline__c.field-meta.xml
<CustomField>
    <fullName>Baseline__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Baseline</label>
    <referenceTo>FundingBaseline__c</referenceTo>
    <relationshipLabel>Baseline Measure Detail (Baseline)</relationshipLabel>
    <relationshipName>Baseline_Measure_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BaselineMeasureDetail__c/fields/Funding_Award__c.field-meta.xml
<CustomField>
    <fullName>Funding_Award__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Funding Award</label>
    <referenceTo>FundingAward</referenceTo>
    <relationshipLabel>Baseline Measure Detail</relationshipLabel>
    <relationshipName>Baseline_Measure_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BaselineMeasureDetail__c/fields/Funding_Baseline__c.field-meta.xml
<CustomField>
    <fullName>Funding_Baseline__c</fullName>
    <label>Funding Baseline</label>
    <referenceTo>FundingBaseline__c</referenceTo>
    <relationshipLabel>Baseline Measure Detail (Funding Baseline)</relationshipLabel>
    <relationshipName>Baseline_Measure_Types</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BaselineMeasureDetail__c/fields/Measure_KPI_Number__c.field-meta.xml
<CustomField>
    <fullName>Measure_KPI_Number__c</fullName>
    <description>KPI that has a numerical value</description>
    <label>Measure KPI (Number)</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BaselineMeasureDetail__c/fields/Property_Measure_Type__c.field-meta.xml
<CustomField>
    <fullName>Property_Measure_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property Measure Type</label>
    <referenceTo>PropertyMeasureType__c</referenceTo>
    <relationshipLabel>Baseline Measure Detail</relationshipLabel>
    <relationshipName>Property_Measure_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Funding_Award_Milestone__c/Funding_Award_Milestone__c.object-meta.xml
<CustomObject>
    <label>Funding Award Milestone</label>
    <nameField>
        <displayFormat>FAM-{00000}</displayFormat>
        <label>Funding Award Milestone Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funding Award Milestones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Funding_Award_Milestone__c/fields/Parent_Baseline__c.field-meta.xml
<CustomField>
    <fullName>Parent_Baseline__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Baseline</label>
    <referenceTo>FundingBaseline__c</referenceTo>
    <relationshipLabel>Funding Award Milestones</relationshipLabel>
    <relationshipName>Funding_Award_Milestones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Funding_Award_Milestone_Measure__c/Funding_Award_Milestone_Measure__c.object-meta.xml
<CustomObject>
    <description>Number of Individual Measures associated with a challenge fund milestone record</description>
    <label>Funding Award Milestone Measure</label>
    <nameField>
        <displayFormat>FAMM-{00000}</displayFormat>
        <label>Funding Award Milestone Measure Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funding Award Milestone Measures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Funding_Award_Milestone_Measure__c/fields/Funding_Award_Milestone__c.field-meta.xml
<CustomField>
    <fullName>Funding_Award_Milestone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Funding Award Milestone</label>
    <referenceTo>Funding_Award_Milestone__c</referenceTo>
    <relationshipLabel>Funding Award Milestone Measures</relationshipLabel>
    <relationshipName>Related_Milestone_Measures</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Funding_Award_Milestone_Measure__c/fields/Installed_Measure_Count__c.field-meta.xml
<CustomField>
    <fullName>Installed_Measure_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Number of the measure type that has been installed, that have been reported against the baseline from Trustmark and synced to salesforce as property measures</inlineHelpText>
    <label>Installed Measure Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Funding_Award_Milestone_Measure__c/fields/Property_Measure_Type__c.field-meta.xml
<CustomField>
    <fullName>Property_Measure_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property Measure Type</label>
    <referenceTo>PropertyMeasureType__c</referenceTo>
    <relationshipLabel>Funding Award Milestone Measures</relationshipLabel>
    <relationshipName>Funding_Award_Milestone_Measures</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Funding_Award_Milestone_Measure__c/fields/Target_Measure_Count__c.field-meta.xml
<CustomField>
    <fullName>Target_Measure_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Populated from the parent baselines, baseline measure detail at the time of milestone creation</inlineHelpText>
    <label>Target Measure Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FundingBaseline__c/FundingBaseline__c.object-meta.xml
<CustomObject>
    <description>Object to store initial and revised KPIs for specific time periods for Funding Awards</description>
    <label>Baseline</label>
    <nameField>
        <displayFormat>BAS-{0000}</displayFormat>
        <label>Funding Baseline Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Baselines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FundingBaseline__c/fields/Funding_Award__c.field-meta.xml
<CustomField>
    <fullName>Funding_Award__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Master Detail Relationship to parent Award</description>
    <label>Funding Award</label>
    <referenceTo>FundingAward</referenceTo>
    <relationshipLabel>Baselines</relationshipLabel>
    <relationshipName>Funding_Baselines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FundingBaseline__c/fields/Parent_Baseline__c.field-meta.xml
<CustomField>
    <fullName>Parent_Baseline__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent  Baseline</label>
    <referenceTo>FundingBaseline__c</referenceTo>
    <relationshipLabel>Baselines</relationshipLabel>
    <relationshipName>Funding_Baselines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FundingPropertyDetail__c/FundingPropertyDetail__c.object-meta.xml
<CustomObject>
    <description>Details of relevant property including number of rooms etc. Used as to store details for properties as they relate to the award rather than general address details</description>
    <label>Funding Property Detail</label>
    <nameField>
        <displayFormat>PTY-{000000}</displayFormat>
        <label>Funding Property Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funding Property Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FundingPropertyDetail__c/fields/Baseline__c.field-meta.xml
<CustomField>
    <fullName>Baseline__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Baseline that this property has been allocated to</description>
    <label>Baseline</label>
    <referenceTo>FundingBaseline__c</referenceTo>
    <relationshipLabel>Property Details</relationshipLabel>
    <relationshipName>Funding_Property_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FundingPropertyDetail__c/fields/Funding_Award__c.field-meta.xml
<CustomField>
    <fullName>Funding_Award__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Grant fund that will be financing any required work</description>
    <label>Funding Award</label>
    <referenceTo>FundingAward</referenceTo>
    <relationshipLabel>Funding Property Details</relationshipLabel>
    <relationshipName>Property_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FundingPropertyDetail__c/fields/TM_UPRN__c.field-meta.xml
<CustomField>
    <fullName>TM_UPRN__c</fullName>
    <description>UPRN from TM to match To Trustmark</description>
    <label>TM UPRN</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OS_Candidate_Address__c/OS_Candidate_Address__c.object-meta.xml
<CustomObject>
    <description>Custom object to record OS candidate addresses that have been checked against the OS API  for a funding award</description>
    <label>OS Candidate Address</label>
    <nameField>
        <displayFormat>OSCA-{0000000}</displayFormat>
        <label>OS Candidate Address Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OS Candidate Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OS_Candidate_Address__c/fields/Address_Search_String__c.field-meta.xml
<CustomField>
    <fullName>Address_Search_String__c</fullName>
    <description>The full address line supplied.</description>
    <label>Address Search String</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OS_Candidate_Address__c/fields/Baseline__c.field-meta.xml
<CustomField>
    <fullName>Baseline__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Baseline</label>
    <referenceTo>FundingBaseline__c</referenceTo>
    <relationshipLabel>OS Candidate Addresses</relationshipLabel>
    <relationshipName>OS_Candidate_Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OS_Candidate_Address__c/fields/OS_UPRN__c.field-meta.xml
<CustomField>
    <fullName>OS_UPRN__c</fullName>
    <label>OS UPRN</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property_Measure__c/Property_Measure__c.object-meta.xml
<CustomObject>
    <description>Details of the work to apply a measure type to a property</description>
    <label>Property Measure</label>
    <nameField>
        <displayFormat>PRM-{00000}</displayFormat>
        <label>Property Measure Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Property Measures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Property_Measure__c/fields/Measure_Type_Parent__c.field-meta.xml
<CustomField>
    <fullName>Measure_Type_Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Lookup to the Measure type Parent</inlineHelpText>
    <label>Measure Type Parent</label>
    <referenceTo>PropertyMeasureType__c</referenceTo>
    <relationshipLabel>Property Measure Parents</relationshipLabel>
    <relationshipName>Measure_Type_Parents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property_Measure__c/fields/Property_Detail__c.field-meta.xml
<CustomField>
    <fullName>Property_Detail__c</fullName>
    <label>Property Detail</label>
    <referenceTo>FundingPropertyDetail__c</referenceTo>
    <relationshipLabel>Property Measures</relationshipLabel>
    <relationshipName>Scheme_Measures</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Property_Measure__c/fields/Related_Funding_Award__c.field-meta.xml
<CustomField>
    <fullName>Related_Funding_Award__c</fullName>
    <label>Related Funding Award</label>
    <referenceTo>FundingAward</referenceTo>
    <relationshipLabel>Property Measures</relationshipLabel>
    <relationshipName>Property_Measures</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Property_Measure__c/fields/TM_UPRN__c.field-meta.xml
<CustomField>
    <fullName>TM_UPRN__c</fullName>
    <description>TM UPRN to connect measure to Trustmark</description>
    <label>TM UPRN</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PropertyMeasureType__c/PropertyMeasureType__c.object-meta.xml
<CustomObject>
    <description>Specifies a list of Property Measure Types and related data</description>
    <label>Property Measure Type</label>
    <nameField>
        <label>Measure Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Property Measure Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/GmsMilestoneTriggerHandler_Test.cls
@IsTest
public with sharing class GmsMilestoneTriggerHandler_Test {
    
    @TestSetup
    static void makeData(){

        Schema.Location location = new Schema.Location();
        location.Name = 'Warm Homes';
        insert location;

        PropertyMeasureType__c pmt = new PropertyMeasureType__c();
        pmt.Name = 'Loft Insulation';

        PropertyMeasureType__c pmt2 = new PropertyMeasureType__c();
        pmt2.Name = 'Double Glasing';

        PropertyMeasureType__c pmt3 = new PropertyMeasureType__c();
        pmt3.Name = 'Draughtproofing';
        insert new List<PropertyMeasureType__c>{pmt, pmt2, pmt3};

        FundingAward fa = new FundingAward();
        insert fa;

        FundingBaseline__c fb = new FundingBaseline__c(
            Funding_Award__c = fa.Id
        );
        insert fb;

        BaselineMeasureDetail__c bmd = new BaselineMeasureDetail__c(
            Property_Measure_Type__c = pmt.Id,
            Measure_KPI_Number__c = 10,
            Funding_Baseline__c = fb.Id
        );

        BaselineMeasureDetail__c bmd2 = new BaselineMeasureDetail__c(
            Property_Measure_Type__c = pmt2.Id,
            Measure_KPI_Number__c = 20,
            Funding_Baseline__c = fb.Id
        );

        BaselineMeasureDetail__c bmd3 = new BaselineMeasureDetail__c(
            Property_Measure_Type__c = pmt3.Id,
            Measure_KPI_Number__c = 10,
            Funding_Baseline__c = fb.Id
        );

        insert new List<BaselineMeasureDetail__c>{bmd, bmd2, bmd3};

        OS_Candidate_Address__c os = new OS_Candidate_Address__c(
            OS_UPRN__c = '1',
            Baseline__c = fb.Id,
            Address_Search_String__c = '1 X1 1XX'
        );

        OS_Candidate_Address__c os2 = new OS_Candidate_Address__c(
            OS_UPRN__c = '2',
            Baseline__c = fb.Id,
            Address_Search_String__c = '2 X1 1XX'
        );

        OS_Candidate_Address__c os3 = new OS_Candidate_Address__c(
            OS_UPRN__c = '3',
            Baseline__c = fb.Id,
            Address_Search_String__c = '3 X1 1XX'
        );
        insert new List<OS_Candidate_Address__c>{os, os2, os3};

        FundingPropertyDetail__c fpd = new FundingPropertyDetail__c(
            Baseline__c = fb.Id,
            Funding_Award__c = fa.Id,
            TM_UPRN__c = '1'
        );
        FundingPropertyDetail__c fpd2 = new FundingPropertyDetail__c(
            Baseline__c = fb.Id,
            Funding_Award__c = fa.Id,
            TM_UPRN__c = '2'
        );
        FundingPropertyDetail__c fpd3 = new FundingPropertyDetail__c(
            Baseline__c = fb.Id,
            Funding_Award__c = fa.Id,
            TM_UPRN__c = '3'
        );
        insert new List<FundingPropertyDetail__c>{fpd, fpd2, fpd3};

        Property_Measure__c pm = new Property_Measure__c(
            Measure_Type_Parent__c = pmt.Id,
            Property_Detail__c = fpd.Id,
            Related_Funding_Award__c = fa.Id
        );
        Property_Measure__c pm2 = new Property_Measure__c(
            Measure_Type_Parent__c = pmt2.Id,
            Property_Detail__c = fpd.Id,
            Related_Funding_Award__c = fa.Id
        );
        Property_Measure__c pm3 = new Property_Measure__c(
            Measure_Type_Parent__c = pmt3.Id,
            Property_Detail__c = fpd.Id,
            Related_Funding_Award__c = fa.Id
        );
        Property_Measure__c pm4 = new Property_Measure__c(
            Measure_Type_Parent__c = pmt2.Id,
            Property_Detail__c = fpd2.Id,
            Related_Funding_Award__c = fa.Id
        );
        Property_Measure__c pm5 = new Property_Measure__c(
            Measure_Type_Parent__c = pmt.Id,
            Property_Detail__c = fpd2.Id,
            Related_Funding_Award__c = fa.Id
        );
        Property_Measure__c pm6 = new Property_Measure__c(
            Measure_Type_Parent__c = pmt.Id,
            Property_Detail__c = fpd3.Id,
            Related_Funding_Award__c = fa.Id
        );

        insert new List<Property_Measure__c>{pm, pm2, pm3, pm4, pm5, pm6};

    }   
    
    @IsTest
    public static void onAfterInsert(){
        FundingBaseline__c baseline = [SELECT Id FROM FundingBaseline__c LIMIT 1];
        List<FundingPropertyDetail__c> properties = [SELECT Baseline__c FROM FundingPropertyDetail__c];
        for (FundingPropertyDetail__c property : properties){
            property.Baseline__c = baseline.Id;
        }
        update properties;
        
        Funding_Award_Milestone__c fm = new Funding_Award_Milestone__c(
            Parent_Baseline__c = baseline.Id
        );

        Test.startTest();
        insert new list<Funding_Award_Milestone__c>{fm};
        Test.stopTest();
        List<Funding_Award_Milestone_Measure__c> famms = [SELECT Id, Funding_Award_Milestone__c, Property_Measure_Type__c, Target_Measure_Count__c, Installed_Measure_Count__c FROM Funding_Award_Milestone_Measure__c];
        Assert.areEqual(3, famms.size(), 'the number of milestone measures created');
        List<Funding_Award_Milestone_Measure__c> famms2 = [SELECT Id, Funding_Award_Milestone__c, Property_Measure_Type__c, Target_Measure_Count__c, Installed_Measure_Count__c FROM Funding_Award_Milestone_Measure__c WHERE Property_Measure_Type__r.Name = 'Loft Insulation'];
        Assert.areEqual(3, famms2[0].Installed_Measure_Count__c, 'installed measure count for Loft insulation');
        List<Funding_Award_Milestone_Measure__c> famms3 = [SELECT Id, Funding_Award_Milestone__c, Property_Measure_Type__c, Target_Measure_Count__c, Installed_Measure_Count__c FROM Funding_Award_Milestone_Measure__c WHERE Property_Measure_Type__r.Name = 'Double Glasing'];
        Assert.areEqual(2, famms3[0].Installed_Measure_Count__c, 'installed measure count for Double Glasing');
        List<Funding_Award_Milestone_Measure__c> famms4 = [SELECT Id, Funding_Award_Milestone__c, Property_Measure_Type__c, Target_Measure_Count__c, Installed_Measure_Count__c FROM Funding_Award_Milestone_Measure__c WHERE Property_Measure_Type__r.Name = 'Draughtproofing'];
        Assert.areEqual(1, famms4[0].Installed_Measure_Count__c, 'installed measure count for Draughtproofing');
    }
}