force-app/main/default/objects/BaselineMeasureDetail__c/BaselineMeasureDetail__c.object-meta.xml
<CustomObject>
    <description>Headline number for each measure included in the phase: EWI, CWI, Underfloor insulation, Loft insulation, Draught proofing, ASHP, GSHP, SGL, Storage heaters*(TBC), Solar PV, Solar Thermal, Windows, Ventilation, Other</description>
    <label>Baseline Measure Detail</label>
    <nameField>
        <displayFormat>MSD-{000000}</displayFormat>
        <label>Measure Detail Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Baseline Measure Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BaselineMeasureDetail__c/fields/Baseline__c.field-meta.xml
<CustomField>
    <fullName>Baseline__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Baseline</label>
    <referenceTo>FundingBaseline__c</referenceTo>
    <relationshipLabel>Baseline Measure Detail (Baseline)</relationshipLabel>
    <relationshipName>Baseline_Measure_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BaselineMeasureDetail__c/fields/Cost_to_install_measure__c.field-meta.xml
<CustomField>
    <fullName>Cost_to_install_measure__c</fullName>
    <inlineHelpText>The figures entered into the &apos;Cost to install measure&apos; column should be best estimate averages, and the costs listed for this question are for information only, rather than forming part of the detailed baseline for this phase of the project.</inlineHelpText>
    <label>Cost to install measure</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/BaselineMeasureDetail__c/fields/Funding_Award__c.field-meta.xml
<CustomField>
    <fullName>Funding_Award__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Funding Award</label>
    <referenceTo>FundingAward</referenceTo>
    <relationshipLabel>Baseline Measure Detail</relationshipLabel>
    <relationshipName>Baseline_Measure_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BaselineMeasureDetail__c/fields/Funding_Baseline__c.field-meta.xml
<CustomField>
    <fullName>Funding_Baseline__c</fullName>
    <label>Funding Baseline</label>
    <referenceTo>FundingBaseline__c</referenceTo>
    <relationshipLabel>Baseline Measure Detail (Funding Baseline)</relationshipLabel>
    <relationshipName>Baseline_Measure_Types</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BaselineMeasureDetail__c/fields/Measure_KPI_Number__c.field-meta.xml
<CustomField>
    <fullName>Measure_KPI_Number__c</fullName>
    <description>KPI that has a numerical value</description>
    <label>Measure KPI (Number)</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BaselineMeasureDetail__c/fields/Measure_Type__c.field-meta.xml
<CustomField>
    <fullName>Measure_Type__c</fullName>
    <description>Depreciated - Predefined list of measure types</description>
    <label>Measure Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Property_Measure_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/BaselineMeasureDetail__c/fields/Property_Measure_Type__c.field-meta.xml
<CustomField>
    <fullName>Property_Measure_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property Measure Type</label>
    <referenceTo>PropertyMeasureType__c</referenceTo>
    <relationshipLabel>Baseline Measure Detail</relationshipLabel>
    <relationshipName>Property_Measure_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BaselineMeasureDetail__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Historic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Change_Control_Request_Line_Item__c/Change_Control_Request_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Change Control Request Line Item</label>
    <nameField>
        <displayFormat>CRLIN-{000000}</displayFormat>
        <label>Change Control Request Line Item No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Change Control Request Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Change_Control_Request_Line_Item__c/fields/Baseline__c.field-meta.xml
<CustomField>
    <fullName>Baseline__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Baseline</label>
    <referenceTo>FundingBaseline__c</referenceTo>
    <relationshipLabel>Change Control Request Line Items</relationshipLabel>
    <relationshipName>Change_Control_Request_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Change_Control_Request_Line_Item__c/fields/Baseline_Measure_Description__c.field-meta.xml
<CustomField>
    <fullName>Baseline_Measure_Description__c</fullName>
    <description>Populated from CCR form and will be a mirror of the related baseline measure records description.</description>
    <label>Baseline Measure Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Change_Control_Request_Line_Item__c/fields/Baseline_Measure_Detail__c.field-meta.xml
<CustomField>
    <fullName>Baseline_Measure_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Baseline Measure Detail</label>
    <referenceTo>BaselineMeasureDetail__c</referenceTo>
    <relationshipLabel>Change Control Request Line Items</relationshipLabel>
    <relationshipName>Change_Control_Request_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Change_Control_Request_Line_Item__c/fields/Cost_To_Install_Measure__c.field-meta.xml
<CustomField>
    <fullName>Cost_To_Install_Measure__c</fullName>
    <label>Cost To Install Measure</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Change_Control_Request_Line_Item__c/fields/Is_Delete_Change__c.field-meta.xml
<CustomField>
    <fullName>Is_Delete_Change__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Represents a change that is a deletion of a record</description>
    <inlineHelpText>Represents a change that is a deletion of a record</inlineHelpText>
    <label>Is Delete Change</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Change_Control_Request_Line_Item__c/fields/Measure_KPI_Number__c.field-meta.xml
<CustomField>
    <fullName>Measure_KPI_Number__c</fullName>
    <description>KPI that has a numerical value</description>
    <label>Measure KPI (Number)</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Change_Control_Request_Line_Item__c/fields/Measure_Type__c.field-meta.xml
<CustomField>
    <fullName>Measure_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Populated from the change request form when a change involves a measure detail change. The value will mirror the type field on related baseline mirror object.</description>
    <label>Property Measure Type</label>
    <referenceTo>PropertyMeasureType__c</referenceTo>
    <relationshipLabel>Change Control Request Line Items</relationshipLabel>
    <relationshipName>Change_Control_Request_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Change_Control_Request_Line_Item__c/fields/Property_Measure_Type__c.field-meta.xml
<CustomField>
    <fullName>Property_Measure_Type__c</fullName>
    <description>Populated from the change request form when a change involves a measure detail change. The value will mirror the type field on related baseline mirror object.</description>
    <label>Measure Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Property_Measure_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FundingBaseline__c/FundingBaseline__c.object-meta.xml
<CustomObject>
    <description>Object to store initial and revised KPIs for specific time periods for Funding Awards</description>
    <label>Baseline</label>
    <nameField>
        <displayFormat>BAS-{0000}</displayFormat>
        <label>Funding Baseline Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Baselines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FundingBaseline__c/fields/Funding_Award__c.field-meta.xml
<CustomField>
    <fullName>Funding_Award__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Master Detail Relationship to parent Award</description>
    <label>Funding Award</label>
    <referenceTo>FundingAward</referenceTo>
    <relationshipLabel>Baselines</relationshipLabel>
    <relationshipName>Funding_Baselines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FundingBaseline__c/fields/Previous_Baseline__c.field-meta.xml
<CustomField>
    <fullName>Previous_Baseline__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Previous Baseline</label>
    <referenceTo>FundingBaseline__c</referenceTo>
    <relationshipLabel>Baselines (Previous Baseline)</relationshipLabel>
    <relationshipName>Baselines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FundingBaseline__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Historic</fullName>
            </value>
            <value>
                <fullName>Pending Submission</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Milestones Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Property_Measure_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>External Wall Insulation</fullName>
    </customValue>
    <customValue>
        <fullName>Cavity Wall Insulation</fullName>
    </customValue>
    <customValue>
        <fullName>Underfloor insulation</fullName>
    </customValue>
    <customValue>
        <fullName>Loft insulation</fullName>
    </customValue>
    <customValue>
        <fullName>Draughtproofing</fullName>
    </customValue>
    <customValue>
        <fullName>Air Source Heat Pump</fullName>
    </customValue>
    <customValue>
        <fullName>Ground Source Heat Pump</fullName>
    </customValue>
    <customValue>
        <fullName>Secondary Glazing</fullName>
    </customValue>
    <customValue>
        <fullName>Storage heaters*(TBC)</fullName>
    </customValue>
    <customValue>
        <fullName>Solar PV</fullName>
    </customValue>
    <customValue>
        <fullName>Solar Thermal</fullName>
    </customValue>
    <customValue>
        <fullName>Windows</fullName>
    </customValue>
    <customValue>
        <fullName>Ventilation</fullName>
    </customValue>
    <customValue>
        <fullName>Wet Central Heating</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Additional Capital Expenditure</fullName>
    </customValue>
    <customValue>
        <fullName>Double Glazing</fullName>
    </customValue>
    <customValue>
        <fullName>High heat retention storage heaters</fullName>
    </customValue>
    <customValue>
        <fullName>Shared Ground loops</fullName>
    </customValue>
    <masterLabel>Property Measure Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/GmsCcrMeasureDetailApproval.cls
public without sharing class GmsCcrMeasureDetailApproval {

    @InvocableMethod(label='Create Baseline Measure Details From CCR Items')
    public static List<Output> createBaselineMeasureDetailsFromItems(List<Input> inputs){
        List<Output> outputs = new List<Output>();
        Input input = inputs.get(0);

        Set<Id> baselineIds = new Set<Id>();
        for (Change_Control_Request_Line_Item__c item : input.measureItems){
            baselineIds.add(item.Baseline__c);
        }

        Map<Id, Id> newBaselineVersions = new Map<Id, Id>();
        List<FundingBaseline__c> baselines = [SELECT Id, Previous_Baseline__c FROM FundingBaseline__c WHERE Previous_Baseline__c IN :baselineIds];
        for (FundingBaseline__c baseline : baselines){
            if (baseline.Previous_Baseline__c != null){
                newBaselineVersions.put(baseline.Previous_Baseline__c, baseline.Id);
            }
        }

        List<BaselineMeasureDetail__c> forUpdate = new List<BaselineMeasureDetail__c>();
        Map<Change_Control_Request_Line_Item__c, BaselineMeasureDetail__c> forInsert = new Map<Change_Control_Request_Line_Item__c, BaselineMeasureDetail__c>();
        List<BaselineMeasureDetail__c> forDelete = new List<BaselineMeasureDetail__c>();

        for (Change_Control_Request_Line_Item__c item : input.measureItems){
            BaselineMeasureDetail__c bmd = new BaselineMeasureDetail__c(
                Measure_KPI_Number__c = item.Measure_KPI_Number__c,
                Id = item.Baseline_Measure_Detail__c,
                Measure_Type__c = item.Property_Measure_Type__c,
                Description__c = item.Baseline_Measure_Description__c,
                Cost_to_install_measure__c = item.Cost_To_Install_Measure__c,
                Status__c = 'Active',
                Funding_Award__c = input.fundingAwardId,
                Funding_Baseline__c = newBaselineVersions.get(item.Baseline__c) ?? item.Baseline__c
            );

            if (bmd.Id == null){
                forInsert.put(item, bmd);
            }else{
                forUpdate.add(bmd);
            }
            if (item.Is_Delete_Change__c && bmd.Id != null){
                forDelete.add(bmd);
            }
        }

        update forUpdate;
        insert forInsert.values();
        delete forDelete;

        List<Change_Control_Request_Line_Item__c> itemsToUpdate = new List<Change_Control_Request_Line_Item__c>();
        for (Change_Control_Request_Line_Item__c item : forInsert.keySet()){
            item.Baseline_Measure_Detail__c = forInsert?.get(item)?.Id;
            itemsToUpdate.add(item);
        }

        update itemsToUpdate;

        Output output = new Output();
        output.measureDetails.addAll(forUpdate);
        outputs.add(output);

        return outputs; 
    }

    public class Input{
        @InvocableVariable
        public List<Change_Control_Request_Line_Item__c> measureItems;
        @InvocableVariable
        public Id fundingAwardId;
    }

    public class Output{
        @InvocableVariable
        public List<BaselineMeasureDetail__c> measureDetails;
        public Output(){
            measureDetails = new List<BaselineMeasureDetail__c>();
        }
    }
}