force-app/main/default/objects/Chat__c/Chat__c.object-meta.xml
<CustomObject>
    <description>Stores a conversation relating to a given record with the system</description>
    <label>Chat</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Chat No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chats</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Chat__c/fields/Context_Child__c.field-meta.xml
<CustomField>
    <fullName>Context_Child__c</fullName>
    <externalId>true</externalId>
    <label>Context Child</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chat__c/fields/Context_Parent__c.field-meta.xml
<CustomField>
    <fullName>Context_Parent__c</fullName>
    <externalId>true</externalId>
    <label>Context Parent</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chat__c/fields/Last_Message__c.field-meta.xml
<CustomField>
    <fullName>Last_Message__c</fullName>
    <inlineHelpText>The datetime the last message on this chat record was sent</inlineHelpText>
    <label>Last Message</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Chat__c/fields/Messages__c.field-meta.xml
<CustomField>
    <fullName>Messages__c</fullName>
    <description>Json formatted messages from the chat</description>
    <label>Messages</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/ChatRecord.cls
public without sharing class ChatRecord {
    
    public static ChatMessaging messaging = new ChatMessaging(); // this is injectable

    @AuraEnabled
    public String summary {get; set;}

    @AuraEnabled
    public String chatId {get; set;}

    @AuraEnabled
    public String messagesJSON {get; set;}

    @AuraEnabled
    public List<ChatMessage> messages {get; set;}

    @AuraEnabled
    public DateTime lastMessage {get; set;}

    @AuraEnabled
    public String contextParent {get; set;}

    @AuraEnabled
    public String contextChild {get; set;}

    @AuraEnabled
    public String contextParentName {get; set;}

    @AuraEnabled
    public String awardeeName {get; set;}

    @AuraEnabled
    public Integer unreadMessageCount {get; set;}


    private Integer sortDirection = 1; // 1 is earliest at top, -1 earliest at bottom

    public ChatRecord(Chat__c chat){
        this.chatId = chat.Id;
        this.contextParent = chat.Context_Parent__c;
        this.messagesJSON = chat.Messages__c; 
        this.messages = messaging.get(chat);
        this.summary = createChatSummary(this.messages); 
        this.lastMessage =  chat.Last_Message__c; 
        this.contextChild = chat.Context_Child__c;
        //this.unreadMessageCount = 
    }

    public ChatRecord(String contextParent){
        this.chatId = null;
        this.contextParent = contextParent;
        this.summary = 'No Messages'; 
        this.lastMessage =  null; 
    }

    @testvisible
    private String isoToJavaDateString(String isoDateTime){
        return isoDateTime.left(10) + ' ' + isoDateTime.mid(11, 8);
    }

    private String createChatSummary(List<ChatMessage> messages){
        
        if(messages.size() >0){
            String summary = messages[messages.size() - 1].body; 
            return summary;
        }
        else{
            return 'No Messages';
        }
        
    }

}