force-app/main/default/objects/Chat__c/Chat__c.object-meta.xml
<CustomObject>
    <description>Stores a conversation relating to a given record with the system</description>
    <label>Chat</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Chat No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chats</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FundingBaseline__c/FundingBaseline__c.object-meta.xml
<CustomObject>
    <description>Object to store initial and revised KPIs for specific time periods for Funding Awards</description>
    <label>Baseline</label>
    <nameField>
        <displayFormat>BAS-{0000}</displayFormat>
        <label>Funding Baseline Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Baselines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FundingBaseline__c/fields/Funding_Award__c.field-meta.xml
<CustomField>
    <fullName>Funding_Award__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Master Detail Relationship to parent Award</description>
    <label>Funding Award</label>
    <referenceTo>FundingAward</referenceTo>
    <relationshipLabel>Baselines</relationshipLabel>
    <relationshipName>Funding_Baselines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FundingBaseline__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Historic</fullName>
            </value>
            <value>
                <fullName>Pending Submission</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Milestones Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FundingBatch__c/FundingBatch__c.object-meta.xml
<CustomObject>
    <description>A request for funds by a local authority for the upgrade of a group of similar houses, specifying home and upgrade types, including costs and numbers for each.</description>
    <label>Batch</label>
    <nameField>
        <displayFormat>ABS-{00000000}</displayFormat>
        <label>ABS Batch Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FundingBatch__c/fields/Active_Baseline__c.field-meta.xml
<CustomField>
    <fullName>Active_Baseline__c</fullName>
    <label>Active Baseline</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FundingBaseline__c.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FundingBaseline__c</referenceTo>
    <relationshipLabel>Batches (Active Baseline)</relationshipLabel>
    <relationshipName>ABS_Batches</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FundingBatch__c/fields/Funding_Award__c.field-meta.xml
<CustomField>
    <fullName>Funding_Award__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Funding Award</label>
    <referenceTo>FundingAward</referenceTo>
    <relationshipLabel>Batches</relationshipLabel>
    <relationshipName>Batches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ChatGetNotificationLinksAction_Test.cls
@istest
public with sharing class ChatGetNotificationLinksAction_Test {
    @istest 
    public static void getNotificationLinks_noChildContext(){
        FundingAward fa = new FundingAward();
        insert fa;

        Chat__c chat = ChatMessaging_Test.newChat(fa.Id, null, 1);
        List<Chat__c> chats = new List<Chat__c>{chat};
        
        ChatMessage message1 = new ChatMessage();
        message1.body = 'message text 1';
        message1.contextParent = fa.Id;
        List<ChatMessage> messages = new List<ChatMessage>{message1};


        ChatGetNotificationLinksAction.chatMessaging = (ChatMessaging)Stub.builder()
            .handleMethod('get').with(messages)
            .create(ChatMessaging.class);

        Test.startTest();
        List<ChatGetNotificationLinksAction.Links> links = ChatGetNotificationLinksAction.getNotificationLinks(new List<List<Chat__c>>{chats});
        Test.stopTest();
        ChatGetNotificationLinksAction.Links firstLinks = links.get(0);
        List<String> tableRows = firstLinks.tableRows;
        Assert.isTrue(tableRows.get(0).contains('href="/' + fa.Id + '"'), 'expect the returned row to contain an a tag with a href of /' + fa.Id);
    }

    @istest
    public static void getNotificationLinks_ChildContextWithMultipleMessages(){
        FundingAward fa = new FundingAward();
        insert fa;

        FundingBaseline__c baseline = new FundingBaseline__c(Status__c = 'Active');
        insert baseline;

        FundingBatch__c fb = new FundingBatch__c(Funding_Award__c = fa.Id, Active_Baseline__c = baseline.Id);
        insert fb;

        Chat__c chat = ChatMessaging_Test.newChat(fa.Id, null, 1);
        List<Chat__c> chats = new List<Chat__c>{chat};
        
        ChatMessage message1 = new ChatMessage();
        message1.body = 'message text 1';
        message1.contextParent = fa.Id;
        message1.contextChild = fb.Id;
        String yesterday =  JSON.serialize(Datetime.now().addDays(-1));
        message1.createdDatetime = yesterday.removeStart('"').removeEnd('"');

        ChatMessage latestMessage = new ChatMessage();
        latestMessage.body = 'latest message';
        latestMessage.contextParent = fa.Id;
        latestMessage.contextChild = fb.Id;
        String now =  JSON.serialize(Datetime.now());
        latestMessage.createdDatetime = now.removeStart('"').removeEnd('"');
        List<ChatMessage> messages = new List<ChatMessage>{message1, latestMessage};


        ChatGetNotificationLinksAction.chatMessaging = (ChatMessaging)Stub.builder()
            .handleMethod('get').with(messages)
            .create(ChatMessaging.class);

        Test.startTest();
        List<ChatGetNotificationLinksAction.Links> links = ChatGetNotificationLinksAction.getNotificationLinks(new List<List<Chat__c>>{chats});
        Test.stopTest();
        ChatGetNotificationLinksAction.Links firstLinks = links.get(0);
        List<String> tableRows = firstLinks.tableRows;
        Assert.isTrue(tableRows.get(0).contains('href="/' + fb.Id + '"'), 'expect the returned row to contain an a tag with a href of /' + fb.Id);
        Assert.isTrue(tableRows.get(0).contains(latestMessage.body), 'expect the returned row to contain the body of the latest message on the child context \'' + latestMessage.body + '\'');
    }
}